class C2S_CONNECTION_Message : google::protobuf::Message { void* vtable[17]; };
class C2S_CONNECTION_Message_t : C2S_CONNECTION_Message { void* vtable[17]; };
class C2S_CONNECTION_Message_t : CNetMessagePB<-1,C2S_CONNECTION_Message,0,1,0>, C2S_CONNECTION_Message { void* vtable[5]; };
class C2S_CONNECT_Message : google::protobuf::Message { void* vtable[17]; };
class C2S_CONNECT_Message_t : C2S_CONNECT_Message { void* vtable[17]; };
class C2S_CONNECT_Message_t : CNetMessagePB<-1,C2S_CONNECT_Message,0,1,0>, C2S_CONNECT_Message { void* vtable[5]; };
class C2S_CONNECT_SameProcessCheck : google::protobuf::Message { void* vtable[17]; };
class CAppSystemDict { void* vtable[7]; };
class CAsyncCallJob<class CHLTVServerAsync,CHLTVServerAsync::RunFrameJob_t> : CThreadedJobWithDependencies, CRefCountServiceBase<CRefMT> { void* vtable[9]; };
class CAsyncCallJob<class CServerSideClient,CServerSideClient::SendSnapshotJob_Empty_t> : CThreadedJobWithDependencies, CRefCountServiceBase<CRefMT> { void* vtable[9]; };
class CAsyncCallJob<class CServerSideClient,CServerSideClient::SendSnapshotJob_HltvReplay_t> : CThreadedJobWithDependencies, CRefCountServiceBase<CRefMT> { void* vtable[9]; };
class CAsyncCallJob<class CServerSideClient,CServerSideClient::SendSnapshotJob_HltvSource_t> : CThreadedJobWithDependencies, CRefCountServiceBase<CRefMT> { void* vtable[9]; };
class CAsyncShaderCompilePrerequisite : IPrerequisite, IRenderAsyncShaderCompileListener { void* vtable[6]; };
class CAsyncShaderCompilePrerequisite : IRenderAsyncShaderCompileListener { void* vtable[1]; };
class CAttributeDictSaveDataOps : CDefSaveRestoreOps { void* vtable[6]; };
class CBannedUsersFilter : IBannedUsersFilter { void* vtable[5]; };
class CBaseCmdKeyValues<class CCLCMsg_CmdKeyValues> : CCLCMsg_CmdKeyValues { void* vtable[17]; };
class CBaseCmdKeyValues<class CSVCMsg_CmdKeyValues> : CSVCMsg_CmdKeyValues { void* vtable[17]; };
class CBaseCmdKeyValues<class CSVCMsg_GameSessionConfiguration> : CSVCMsg_GameSessionConfiguration { void* vtable[17]; };
class CBaseEngineService<class IBenchmarkService> : CTier4AppSystem<IBenchmarkService,0> { void* vtable[24]; };
class CBaseEngineService<class IEngineService> : CTier4AppSystem<IEngineService,0> { void* vtable[23]; };
class CBaseEngineService<class IGameResourceService> : CTier4AppSystem<IGameResourceService,0> { void* vtable[44]; };
class CBaseEngineService<class IGameUIService> : CTier4AppSystem<IGameUIService,0> { void* vtable[39]; };
class CBaseEngineService<class IInputService> : CTier4AppSystem<IInputService,0> { void* vtable[62]; };
class CBaseEngineService<class IMapListService> : CTier4AppSystem<IMapListService,0> { void* vtable[26]; };
class CBaseEngineService<class INetworkClientService> : CTier4AppSystem<INetworkClientService,0> { void* vtable[64]; };
class CBaseEngineService<class INetworkP2PService> : CTier4AppSystem<INetworkP2PService,0> { void* vtable[33]; };
class CBaseEngineService<class INetworkServerService> : CTier4AppSystem<INetworkServerService,0> { void* vtable[51]; };
class CBaseEngineService<class INetworkService> : CTier4AppSystem<INetworkService,0> { void* vtable[24]; };
class CBaseEngineService<class IRenderService> : CTier4AppSystem<IRenderService,0> { void* vtable[37]; };
class CBaseEngineService<class ISoundService> : CTier4AppSystem<ISoundService,0> { void* vtable[36]; };
class CBaseEngineService<class ISplitScreenService> : CTier4AppSystem<ISplitScreenService,0> { void* vtable[43]; };
class CBaseEngineService<class IStatsService> : CTier4AppSystem<IStatsService,0> { void* vtable[27]; };
class CBaseEngineService<class IToolService> : CTier4AppSystem<IToolService,0> { void* vtable[91]; };
class CBaseEngineService<class IVProfService> : CTier4AppSystem<IVProfService,0> { void* vtable[25]; };
class CBaseSpawnGroup : ISpawnGroup, IComputeWorldOriginCallback, IGameResourceManifestLoadCompletionCallback { void* vtable[45]; };
class CBaseSpawnGroup : IGameResourceManifestLoadCompletionCallback { void* vtable[2]; };
class CBaseSpawnGroup : IComputeWorldOriginCallback { void* vtable[1]; };
class CBaseVModuleMetadataProvider { void* vtable[1]; };
class CBenchmarkService : CBaseEngineService<IBenchmarkService> { void* vtable[24]; };
class CBidirMsg_PredictionEvent : google::protobuf::Message { void* vtable[17]; };
class CBidirMsg_RebroadcastGameEvent : google::protobuf::Message { void* vtable[17]; };
class CBidirMsg_RebroadcastGameEvent_t : CBidirMsg_RebroadcastGameEvent { void* vtable[17]; };
class CBidirMsg_RebroadcastGameEvent_t : CNetMessagePB<16,CBidirMsg_RebroadcastGameEvent,5,1,1>, CBidirMsg_RebroadcastGameEvent { void* vtable[5]; };
class CBidirMsg_RebroadcastSource : google::protobuf::Message { void* vtable[17]; };
class CBidirMsg_RebroadcastSource_t : CBidirMsg_RebroadcastSource { void* vtable[17]; };
class CBidirMsg_RebroadcastSource_t : CNetMessagePB<17,CBidirMsg_RebroadcastSource,5,1,1>, CBidirMsg_RebroadcastSource { void* vtable[5]; };
class CBreakpadPassiveAssertionFailureListener : IAssertionFailureListener { void* vtable[3]; };
class CBroadcastPlayer : IDemoPlayer, IBroadcastPlayer { void* vtable[43]; };
class CBroadcastPlayer : IBroadcastPlayer { void* vtable[5]; };
class CBugService : CBaseEngineService<IEngineService>, IVConCommDataReceived, IScreenshotCallback, IVoiceTarget { void* vtable[23]; };
class CBugService : IScreenshotCallback { void* vtable[5]; };
class CBugService : IVoiceTarget { void* vtable[2]; };
class CBugService : IVConCommDataReceived { void* vtable[1]; };
class CCLCMsg_BaselineAck : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_BaselineAck_t : CCLCMsg_BaselineAck { void* vtable[17]; };
class CCLCMsg_BaselineAck_t : CNetMessagePB<23,CCLCMsg_BaselineAck,16,1,0>, CCLCMsg_BaselineAck { void* vtable[5]; };
class CCLCMsg_ClientInfo : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_ClientInfo_t : CCLCMsg_ClientInfo { void* vtable[17]; };
class CCLCMsg_ClientInfo_t : CNetMessagePB<20,CCLCMsg_ClientInfo,10,1,0>, CCLCMsg_ClientInfo { void* vtable[5]; };
class CCLCMsg_CmdKeyValues : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_CmdKeyValues_t : CBaseCmdKeyValues<CCLCMsg_CmdKeyValues> { void* vtable[17]; };
class CCLCMsg_CmdKeyValues_t : CNetMessagePB<34,CBaseCmdKeyValues<CCLCMsg_CmdKeyValues>,9,1,0>, CBaseCmdKeyValues<CCLCMsg_CmdKeyValues> { void* vtable[5]; };
class CCLCMsg_Diagnostic : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_Diagnostic_t : CCLCMsg_Diagnostic { void* vtable[17]; };
class CCLCMsg_Diagnostic_t : CNetMessagePB<37,CCLCMsg_Diagnostic,0,1,0>, CCLCMsg_Diagnostic { void* vtable[5]; };
class CCLCMsg_HltvFixupOperatorTick : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_HltvReplay : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_ListenEvents : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_LoadingProgress : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_LoadingProgress_t : CCLCMsg_LoadingProgress { void* vtable[17]; };
class CCLCMsg_LoadingProgress_t : CNetMessagePB<27,CCLCMsg_LoadingProgress,10,1,0>, CCLCMsg_LoadingProgress { void* vtable[5]; };
class CCLCMsg_Move : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_Move_t : CCLCMsg_Move { void* vtable[17]; };
class CCLCMsg_Move_t : CNetMessagePB<21,CCLCMsg_Move,8,0,0>, CCLCMsg_Move { void* vtable[5]; };
class CCLCMsg_RconServerDetails : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_RequestPause : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_RequestPause_t : CCLCMsg_RequestPause { void* vtable[17]; };
class CCLCMsg_RequestPause_t : CNetMessagePB<33,CCLCMsg_RequestPause,0,1,0>, CCLCMsg_RequestPause { void* vtable[5]; };
class CCLCMsg_RespondCvarValue : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_RespondCvarValue_t : CCLCMsg_RespondCvarValue { void* vtable[17]; };
class CCLCMsg_RespondCvarValue_t : CNetMessagePB<25,CCLCMsg_RespondCvarValue,0,1,0>, CCLCMsg_RespondCvarValue { void* vtable[5]; };
class CCLCMsg_ServerStatus : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_ServerStatus_t : CCLCMsg_ServerStatus { void* vtable[17]; };
class CCLCMsg_ServerStatus_t : CNetMessagePB<31,CCLCMsg_ServerStatus,0,1,0>, CCLCMsg_ServerStatus { void* vtable[5]; };
class CCLCMsg_SplitPlayerConnect : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_SplitPlayerConnect_t : CCLCMsg_SplitPlayerConnect { void* vtable[17]; };
class CCLCMsg_SplitPlayerConnect_t : CNetMessagePB<28,CCLCMsg_SplitPlayerConnect,10,1,0>, CCLCMsg_SplitPlayerConnect { void* vtable[5]; };
class CCLCMsg_SplitPlayerDisconnect : google::protobuf::Message { void* vtable[17]; };
class CCLCMsg_SplitPlayerDisconnect_t : CCLCMsg_SplitPlayerDisconnect { void* vtable[17]; };
class CCLCMsg_SplitPlayerDisconnect_t : CNetMessagePB<30,CCLCMsg_SplitPlayerDisconnect,10,1,0>, CCLCMsg_SplitPlayerDisconnect { void* vtable[5]; };
class CCLCMsg_VoiceData : google::protobuf::Message { void* vtable[17]; };
class CCallback<class CSteam3Client,ClientGameServerDeny_t,0> : CCallbackImpl<16> { void* vtable[4]; };
class CCallback<class CSteam3Client,GameOverlayActivated_t,0> : CCallbackImpl<12> { void* vtable[4]; };
class CCallback<class CSteam3Client,GameServerChangeRequested_t,0> : CCallbackImpl<128> { void* vtable[4]; };
class CCallback<class CSteam3Client,LowBatteryPower_t,0> : CCallbackImpl<1> { void* vtable[4]; };
class CCallback<class CSteam3Client,PersonaStateChange_t,0> : CCallbackImpl<16> { void* vtable[4]; };
class CCallback<class CSteam3Client,SocketStatusCallback_t,0> : CCallbackImpl<20> { void* vtable[4]; };
class CCallback<class CSteam3ServerS1,GSPolicyResponse_t,1> : CCallbackImpl<1> { void* vtable[4]; };
class CCallback<class CSteam3ServerS1,SteamServerConnectFailure_t,1> : CCallbackImpl<8> { void* vtable[4]; };
class CCallback<class CSteam3ServerS1,SteamServersConnected_t,1> : CCallbackImpl<1> { void* vtable[4]; };
class CCallback<class CSteam3ServerS1,SteamServersDisconnected_t,1> : CCallbackImpl<4> { void* vtable[4]; };
class CCallback<class CSteam3ServerS1,ValidateAuthTicketResponse_t,1> : CCallbackImpl<20> { void* vtable[4]; };
class CCallbackImpl<128> : CCallbackBase { void* vtable[4]; };
class CCallbackImpl<12> : CCallbackBase { void* vtable[4]; };
class CCallbackImpl<16> : CCallbackBase { void* vtable[4]; };
class CCallbackImpl<1> : CCallbackBase { void* vtable[4]; };
class CCallbackImpl<20> : CCallbackBase { void* vtable[4]; };
class CCallbackImpl<24> : CCallbackBase { void* vtable[4]; };
class CCallbackImpl<4> : CCallbackBase { void* vtable[4]; };
class CCallbackImpl<8> : CCallbackBase { void* vtable[4]; };
class CChangelevelGameClientPrerequisite : IPrerequisite { void* vtable[6]; };
class CClientFrame { void* vtable[2]; };
class CClientFrameManager { void* vtable[1]; };
class CClientOnlyServerConfig : CDefaultServerConfig { void* vtable[29]; };
class CColorizedLoggingListener : CSimpleLoggingListener { void* vtable[5]; };
class CCompressedResourceManifestRefCounted : CRefCounted1<CCompressedResourceManifest,CRefCountServiceBase<CRefMT> >, CRefCountServiceBase<CRefMT> { void* vtable[1]; };
class CConCommandMemberAccessor<class CBannedUsersFilter> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CBannedUsersFilter> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CBugService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CBugService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CGameUIService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CGameUIService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CInputService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CInputService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CLog> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CLog> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CMapListService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CMapListService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CNetworkClientService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CNetworkClientService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CNetworkP2PService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CNetworkP2PService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CNetworkServerService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CNetworkServerService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CRenderService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CRenderService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CRenderingWorldSession> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CRenderingWorldSession> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CScreenshotService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CScreenshotService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CSoundService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CSoundService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CSplitScreenService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CSplitScreenService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CStatsService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CStatsService> : ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CVProfService> : ConCommand, ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CConCommandMemberAccessor<class CVProfService> : ICommandCompletionCallback { void* vtable[1]; };
class CConnectGameClientPrerequisite : IPrerequisite { void* vtable[6]; };
class CConnectRelayPrerequisite : IPrerequisite { void* vtable[6]; };
class CConsoleProcessorForTestScripts : ITestScriptCommandProcessor { void* vtable[1]; };
class CCreateGameClientPrerequisite : IPrerequisite { void* vtable[6]; };
class CDebugVisualizerAbsTime : IDebugVisualizer { void* vtable[6]; };
class CDebugVisualizerMgr : IDebugVisualizerMgr { void* vtable[9]; };
class CDefaultClientConfig : CBaseAppSystem<ISource2ClientConfig> { void* vtable[19]; };
class CDefaultServerConfig : CBaseAppSystem<ISource2ServerConfig> { void* vtable[29]; };
class CDelayedCall2<class CHLTVServerAsync,class CHLTVServerAsync,ITvStreamSource::StartRecordingCall_t,struct empty_t> : CDelayedCallBase<CHLTVServerAsync> { void* vtable[2]; };
class CDelayedCall2<class CNetworkGameServerBase,class CHLTVServer,CHLTVServer::PrintTVStatusCall_t,struct empty_t> : CDelayedCallBase<CNetworkGameServerBase> { void* vtable[2]; };
class CDelayedCall2<class CNetworkGameServerBase,class CNetworkGameServerBase,CNetworkGameServerBase::ClientConnectDelayedCall_t,struct empty_t> : CDelayedCallBase<CNetworkGameServerBase> { void* vtable[2]; };
class CDelayedCall2<class CNetworkGameServerBase,class CNetworkGameServerBase,ITvStreamSource::StartAutoRecordingCall_t,struct empty_t> : CDelayedCallBase<CNetworkGameServerBase> { void* vtable[2]; };
class CDelayedCall2<class CNetworkGameServerBase,class CNetworkGameServerBase,ITvStreamSource::StartRecordingCall_t,struct empty_t> : CDelayedCallBase<CNetworkGameServerBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CHLTVClient,CHLTVClient::PrintTVStatusCall_t,struct empty_t> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClient,CServerSideClient::FakeClientMarkSpawnGroupsAsLoadedCall_t,struct empty_t> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClient,CServerSideClient::StartHltvReplayCall_t,struct empty_t> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClient,CServerSideClient::StopHltvReplayCall_t,struct empty_t> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClientBase,CServerSideClientBase::BuildServerInfoMessageAsync_t,class CNetworkGameServerSpawnGroupAutoLock> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClientBase,CServerSideClientBase::DisconnectCall_t,struct empty_t> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClientBase,CServerSideClientBase::OnSpawnGroupActivateCall_t,class CNetworkGameServerSpawnGroupAutoLock> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClientBase,CServerSideClientBase::OnSpawnGroupDeactivateCall_t,class CNetworkGameServerSpawnGroupAutoLock> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClientBase,CServerSideClientBase::OnSpawnGroupLoadCall_t,class CNetworkGameServerSpawnGroupAutoLock> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClientBase,CServerSideClientBase::ProcessBaselineAckCall_t,struct empty_t> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClientBase,CServerSideClientBase::SendNetMessageCall_t,struct empty_t> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClientBase,CServerSideClientBase::SendSpawnGroupManifestUpdateCall_t,class CNetworkGameServerSpawnGroupAutoLock> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClientBase,CServerSideClientBase::SignonStateNewCall_t,struct empty_t> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClientBase,CServerSideClientBase::SignonStateNewFailedCall_t,struct empty_t> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCall2<class CServerSideClientBase,class CServerSideClientBase,CServerSideClientBase::UpdateAcknowledgedFramecountCall_t,struct empty_t> : CDelayedCallBase<CServerSideClientBase> { void* vtable[2]; };
class CDelayedCallBase<class CHLTVServerAsync> { void* vtable[2]; };
class CDelayedCallBase<class CNetworkGameServerBase> { void* vtable[2]; };
class CDelayedCallBase<class CServerSideClientBase> { void* vtable[2]; };
class CDeltaEntityHeaderReader : CDeltaEntityHeaderReaderBase { void* vtable[1]; };
class CDeltaEntityHeaderWriter : CDeltaEntitysHeaderWriterBase { void* vtable[1]; };
class CDeltaEntityNonTransmitHeaderReader : CDeltaEntityHeaderReaderBase { void* vtable[1]; };
class CDeltaEntityNonTransmitHeaderWriter : CDeltaEntitysHeaderWriterBase { void* vtable[1]; };
class CDemoAnimationData : google::protobuf::Message { void* vtable[17]; };
class CDemoAnimationHeader : google::protobuf::Message { void* vtable[17]; };
class CDemoClassInfo : google::protobuf::Message { void* vtable[17]; };
class CDemoClassInfo_class_t : google::protobuf::Message { void* vtable[17]; };
class CDemoConsoleCmd : google::protobuf::Message { void* vtable[17]; };
class CDemoCustomData : google::protobuf::Message { void* vtable[17]; };
class CDemoCustomDataCallbacks : google::protobuf::Message { void* vtable[17]; };
class CDemoFile : IDemoStream { void* vtable[8]; };
class CDemoFileHeader : google::protobuf::Message { void* vtable[17]; };
class CDemoFileInfo : google::protobuf::Message { void* vtable[17]; };
class CDemoFullPacket : google::protobuf::Message { void* vtable[17]; };
class CDemoMessagePB<0,class CDemoStop> : CDemoStop { void* vtable[17]; };
class CDemoMessagePB<0,class CDemoStop> : IDemoMessage, CDemoStop { void* vtable[6]; };
class CDemoMessagePB<1,class CDemoFileHeader> : CDemoFileHeader { void* vtable[17]; };
class CDemoMessagePB<1,class CDemoFileHeader> : IDemoMessage, CDemoFileHeader { void* vtable[6]; };
class CDemoMessagePB<10,class CDemoCustomData> : CDemoCustomData { void* vtable[17]; };
class CDemoMessagePB<10,class CDemoCustomData> : IDemoMessage, CDemoCustomData { void* vtable[6]; };
class CDemoMessagePB<11,class CDemoCustomDataCallbacks> : CDemoCustomDataCallbacks { void* vtable[17]; };
class CDemoMessagePB<11,class CDemoCustomDataCallbacks> : IDemoMessage, CDemoCustomDataCallbacks { void* vtable[6]; };
class CDemoMessagePB<12,class CDemoUserCmd> : CDemoUserCmd { void* vtable[17]; };
class CDemoMessagePB<12,class CDemoUserCmd> : IDemoMessage, CDemoUserCmd { void* vtable[6]; };
class CDemoMessagePB<13,class CDemoFullPacket> : CDemoFullPacket { void* vtable[17]; };
class CDemoMessagePB<13,class CDemoFullPacket> : IDemoMessage, CDemoFullPacket { void* vtable[6]; };
class CDemoMessagePB<14,class CDemoSaveGame> : CDemoSaveGame { void* vtable[17]; };
class CDemoMessagePB<14,class CDemoSaveGame> : IDemoMessage, CDemoSaveGame { void* vtable[6]; };
class CDemoMessagePB<15,class CDemoSpawnGroups> : CDemoSpawnGroups { void* vtable[17]; };
class CDemoMessagePB<15,class CDemoSpawnGroups> : IDemoMessage, CDemoSpawnGroups { void* vtable[6]; };
class CDemoMessagePB<15,class CDemoSpawnGroupsHLTVBroadcast> : CDemoSpawnGroupsHLTVBroadcast { void* vtable[17]; };
class CDemoMessagePB<15,class CDemoSpawnGroupsHLTVBroadcast> : IDemoMessage, CDemoSpawnGroupsHLTVBroadcast { void* vtable[6]; };
class CDemoMessagePB<16,class CDemoAnimationData> : CDemoAnimationData { void* vtable[17]; };
class CDemoMessagePB<16,class CDemoAnimationData> : IDemoMessage, CDemoAnimationData { void* vtable[6]; };
class CDemoMessagePB<17,class CDemoAnimationHeader> : CDemoAnimationHeader { void* vtable[17]; };
class CDemoMessagePB<17,class CDemoAnimationHeader> : IDemoMessage, CDemoAnimationHeader { void* vtable[6]; };
class CDemoMessagePB<18,class CDemoRecovery> : CDemoRecovery { void* vtable[17]; };
class CDemoMessagePB<18,class CDemoRecovery> : IDemoMessage, CDemoRecovery { void* vtable[6]; };
class CDemoMessagePB<2,class CDemoFileInfo> : CDemoFileInfo { void* vtable[17]; };
class CDemoMessagePB<2,class CDemoFileInfo> : IDemoMessage, CDemoFileInfo { void* vtable[6]; };
class CDemoMessagePB<3,class CDemoSyncTick> : CDemoSyncTick { void* vtable[17]; };
class CDemoMessagePB<3,class CDemoSyncTick> : IDemoMessage, CDemoSyncTick { void* vtable[6]; };
class CDemoMessagePB<4,class CDemoSendTables> : CDemoSendTables { void* vtable[17]; };
class CDemoMessagePB<4,class CDemoSendTables> : IDemoMessage, CDemoSendTables { void* vtable[6]; };
class CDemoMessagePB<5,class CDemoClassInfo> : CDemoClassInfo { void* vtable[17]; };
class CDemoMessagePB<5,class CDemoClassInfo> : IDemoMessage, CDemoClassInfo { void* vtable[6]; };
class CDemoMessagePB<6,class CDemoStringTables> : CDemoStringTables { void* vtable[17]; };
class CDemoMessagePB<6,class CDemoStringTables> : IDemoMessage, CDemoStringTables { void* vtable[6]; };
class CDemoMessagePB<7,class CDemoPacket> : CDemoPacket { void* vtable[17]; };
class CDemoMessagePB<7,class CDemoPacket> : IDemoMessage, CDemoPacket { void* vtable[6]; };
class CDemoMessagePB<9,class CDemoConsoleCmd> : CDemoConsoleCmd { void* vtable[17]; };
class CDemoMessagePB<9,class CDemoConsoleCmd> : IDemoMessage, CDemoConsoleCmd { void* vtable[6]; };
class CDemoPacket : google::protobuf::Message { void* vtable[17]; };
class CDemoPlaybackLoop : IDemoPlaybackLoop { void* vtable[5]; };
class CDemoPlayer : IDemoPlayer, IDemoMessageFileInfo { void* vtable[42]; };
class CDemoPlayer : IDemoMessageFileInfo { void* vtable[1]; };
class CDemoRecorder : IDemoRecorder, IDemoMessageSink { void* vtable[21]; };
class CDemoRecorder : IDemoMessageSink { void* vtable[1]; };
class CDemoRecovery : google::protobuf::Message { void* vtable[17]; };
class CDemoRecovery_DemoInitialSpawnGroupEntry : google::protobuf::Message { void* vtable[17]; };
class CDemoSaveGame : google::protobuf::Message { void* vtable[17]; };
class CDemoSendTables : google::protobuf::Message { void* vtable[17]; };
class CDemoSpawnGroups : google::protobuf::Message { void* vtable[17]; };
class CDemoSpawnGroupsHLTVBroadcast : google::protobuf::Message { void* vtable[17]; };
class CDemoStop : google::protobuf::internal::ZeroFieldsBase { void* vtable[17]; };
class CDemoStreamHttp : IDemoStream { void* vtable[8]; };
class CDemoStreamHttp::CFragmentRequest : CDemoStreamHttp::CPendingRequest { void* vtable[7]; };
class CDemoStreamHttp::CPendingRequest : CCallbackBase { void* vtable[7]; };
class CDemoStreamHttp::CStartRequest : CDemoStreamHttp::CPendingRequest { void* vtable[7]; };
class CDemoStreamHttp::CSyncRequest : CDemoStreamHttp::CPendingRequest { void* vtable[7]; };
class CDemoStringTables : google::protobuf::Message { void* vtable[17]; };
class CDemoStringTables_items_t : google::protobuf::Message { void* vtable[17]; };
class CDemoStringTables_table_t : google::protobuf::Message { void* vtable[17]; };
class CDemoSyncTick : google::protobuf::internal::ZeroFieldsBase { void* vtable[17]; };
class CDemoUserCmd : google::protobuf::Message { void* vtable[17]; };
class CDiskDemoBuffer : IDemoBuffer { void* vtable[15]; };
class CDownloadAddonPrerequisite : IPrerequisite { void* vtable[6]; };
class CEmptyEntityResourceManifest : CEntityResourceManifest { void* vtable[12]; };
class CEngine2MinidumpCommentBuilder : CMiniDumpCommentBuilderBase { void* vtable[3]; };
class CEngineClient : CTier4AppSystem<IVEngineClient2,0> { void* vtable[190]; };
class CEngineConsoleLoggingListener : ILoggingListener { void* vtable[5]; };
class CEngineGameUI : CTier3AppSystem<IEngineGameUI,0> { void* vtable[15]; };
class CEngineGotvSyncPacket : google::protobuf::Message { void* vtable[17]; };
class CEnginePVSManager : IEnginePVSManager { void* vtable[9]; };
class CEngineServer : CTier4AppSystem<IVEngineServer2,0> { void* vtable[121]; };
class CEngineServiceMgr : CTier4AppSystem<IEngineServiceMgr,0>, ILoopModePrerequisiteRegistry { void* vtable[61]; };
class CEngineServiceMgr : ILoopModePrerequisiteRegistry { void* vtable[2]; };
class CEngineSoundServices : ISoundSystemServices { void* vtable[46]; };
class CEngineSoundServicesDebugVisualizer : CDebugVisualizerAbsTime { void* vtable[6]; };
class CEngineSoundServicesDebugVisualizerRel : IDebugVisualizer { void* vtable[6]; };
class CEngineWatchdogThread : CThread { void* vtable[6]; };
class CEntity2_EHandle_Restore : IKV3TransferInterface_EHandle_Load { void* vtable[1]; };
class CEntity2_EHandle_Save : IKV3TransferInterface_EHandle_Save { void* vtable[1]; };
class CEntityComponentHelperT<class CScriptComponent,class CEntityComponentHelperReferenced<class CScriptComponent> > : CEntityComponentHelperReferenced<CScriptComponent> { void* vtable[6]; };
class CEntityInfo { void* vtable[2]; };
class CEntityMETASpewFunctor : CEntityMETAAutoCompletionFunctor, ICommandCallback { void* vtable[1]; };
class CEntityMETASpewFunctor : ICommandCallback { void* vtable[1]; };
class CEntityMsg : google::protobuf::Message { void* vtable[17]; };
class CEntityReadInfo : CEntityInfo { void* vtable[2]; };
class CEntityReport : IEntityReport { void* vtable[6]; };
class CEntityResourceManifest : IEntityResourceManifest { void* vtable[12]; };
class CEntityWriteInfo : CEntityInfo { void* vtable[2]; };
class CFileLoggingListener : IFileLoggingListener { void* vtable[7]; };
class CFinalizeConnectionPrerequisite : IPrerequisite { void* vtable[6]; };
class CFlattenedSerializerSpewFunc_Log : IFlattenedSerializerSpewFunc { void* vtable[3]; };
class CFlattenedSerializerSpewListener<1> : IFlattenedSerializerSpewListener { void* vtable[6]; };
class CFrameMemDumpJob : CThreadedJob, CRefCountServiceBase<CRefMT> { void* vtable[7]; };
class CFrameSnapshotManager : CRefCounted<CRefCountServiceBase<CRefMT> > { void* vtable[1]; };
class CGameClientConnectPrerequisite : CSequentialPrerequisite, IPrerequisiteRegistry { void* vtable[8]; };
class CGameClientConnectPrerequisite : IPrerequisiteRegistry { void* vtable[2]; };
class CGameEventDispatcher : INetMessageDispatcher { void* vtable[1]; };
class CGameEventSystem : CTier4AppSystem<IGameEventSystem,0> { void* vtable[21]; };
class CGameInfo : google::protobuf::Message { void* vtable[17]; };
class CGameInfo_CCSGameInfo : google::protobuf::Message { void* vtable[17]; };
class CGameInfo_CDotaGameInfo : google::protobuf::Message { void* vtable[17]; };
class CGameInfo_CDotaGameInfo_CHeroSelectEvent : google::protobuf::Message { void* vtable[17]; };
class CGameInfo_CDotaGameInfo_CPlayerInfo : google::protobuf::Message { void* vtable[17]; };
class CGameResourceManifestPrerequisite : IPrerequisite { void* vtable[7]; };
class CGameResourceService : CBaseEngineService<IGameResourceService> { void* vtable[44]; };
class CGameUIFuncs : CTier3AppSystem<IGameUIFuncs,0> { void* vtable[17]; };
class CGameUIRenderCallbackGroupLayer : IProceduralLayerRenderer { void* vtable[3]; };
class CGameUIRenderLayer : IProceduralLayerRenderer { void* vtable[3]; };
class CGameUIService : CBaseEngineService<IGameUIService>, IRenderHandler { void* vtable[40]; };
class CGameUIService : IRenderHandler { void* vtable[3]; };
class CGenericExprPart { void* vtable[5]; };
class CGenericExpr_Binary : CGenericExprPart { void* vtable[5]; };
class CGenericExpr_BoolLiteral : CGenericExprPart { void* vtable[5]; };
class CGenericExpr_FloatLiteral : CGenericExprPart { void* vtable[5]; };
class CGenericExpr_FunctionCall : CGenericExprPart { void* vtable[7]; };
class CGenericExpr_IntLiteral : CGenericExprPart { void* vtable[5]; };
class CGenericExpr_Property : CGenericExprPart { void* vtable[5]; };
class CGenericExpr_StringLiteral : CGenericExprPart { void* vtable[5]; };
class CGenericExpr_TernaryConditional : CGenericExprPart { void* vtable[5]; };
class CGenericExpr_Unary : CGenericExprPart { void* vtable[5]; };
class CGenericExpr_VariableReference : CGenericExprPart { void* vtable[5]; };
class CHLTVBroadcast { void* vtable[1]; };
class CHLTVBroadcast::CHttpCallback : CCallbackBase { void* vtable[3]; };
class CHLTVBuildFullFrameSplitJob : CThreadedJob, CRefCountServiceBase<CRefMT> { void* vtable[7]; };
class CHLTVClient : CServerSideClientBase, INetworkChannelNotify, INetworkMessageProcessingPreFilter { void* vtable[79]; };
class CHLTVClient : INetworkMessageProcessingPreFilter { void* vtable[1]; };
class CHLTVClientState : CNetworkGameClientBase, CUtlSlot, INetworkMessageProcessingPreFilter, IConnectionlessPacketHandler, INetworkChannelNotify, IGameEventWatcher { void* vtable[142]; };
class CHLTVClientState : IConnectionlessPacketHandler { void* vtable[2]; };
class CHLTVClientState : IGameEventWatcher { void* vtable[1]; };
class CHLTVClientState : INetworkChannelNotify { void* vtable[1]; };
class CHLTVClientState : INetworkMessageProcessingPreFilter { void* vtable[1]; };
class CHLTVDemoRecorder : IDemoRecorder { void* vtable[21]; };
class CHLTVFrame : CClientFrame { void* vtable[2]; };
class CHLTVServer : CNetworkGameServerBase, IConnectionlessPacketHandler, IConVarListener, IHLTVServer, ITvStreamSink { void* vtable[81]; };
class CHLTVServer : IHLTVServer { void* vtable[21]; };
class CHLTVServer : ITvStreamSink { void* vtable[5]; };
class CHLTVServer : IConVarListener { void* vtable[2]; };
class CHLTVServer : IConnectionlessPacketHandler { void* vtable[2]; };
class CHLTVServerAsync : ITvStreamSource { void* vtable[10]; };
class CHLTVServerAsync::CAsyncCall<CHLTVServerAsync::DumpMemCall_t> : CDelayedCall<CHLTVServerAsync,CHLTVServerAsync::DumpMemCall_t> { void* vtable[2]; };
class CHLTVServerAsync::CAsyncCall<CHLTVServerAsync::PrintBroadcastTVStatusCall_t> : CDelayedCall<CHLTVServerAsync,CHLTVServerAsync::PrintBroadcastTVStatusCall_t> { void* vtable[2]; };
class CHLTVServerAsync::CAsyncCall<CHLTVServerAsync::StartBroadcastCall_t> : CDelayedCall<CHLTVServerAsync,CHLTVServerAsync::StartBroadcastCall_t> { void* vtable[2]; };
class CHLTVServerAsync::CAsyncCall<CHLTVServerAsync::WriteDemoMessageCall_t> : CDelayedCall<CHLTVServerAsync,CHLTVServerAsync::WriteDemoMessageCall_t> { void* vtable[2]; };
class CHLTVServerAsync::CAsyncCall<ITvStreamSource::StartAutoRecordingCall_t> : CDelayedCall<CHLTVServerAsync,ITvStreamSource::StartAutoRecordingCall_t> { void* vtable[2]; };
class CHLTVServerAsync::CAsyncCall<ITvStreamSource::StartRecordingCall_t> : CDelayedCall<CHLTVServerAsync,ITvStreamSource::StartRecordingCall_t> { void* vtable[2]; };
class CHLTVServerAsync::CDeferredCall<CHLTVServerAsync::AppendSpawnGroupMessageCall_t> : CDelayedCall<CHLTVServerAsync,CHLTVServerAsync::AppendSpawnGroupMessageCall_t> { void* vtable[2]; };
class CHLTVServerAsync::CHLTVDemoRecorderProxy : IDemoMessageSink { void* vtable[1]; };
class CHLTVServerAsync::CReverseCall<CHLTVServerAsync::OnStartedRecordingReverseCall_t> : CDelayedCall<CHLTVServerAsync,CHLTVServerAsync::OnStartedRecordingReverseCall_t> { void* vtable[2]; };
class CHLTVServerAsync::CSendClientMessagesJob : CThreadedJobWithDependencies, CRefCountServiceBase<CRefMT> { void* vtable[9]; };
class CHiddenFieldValuePrinter : google::protobuf::TextFormat::FastFieldValuePrinter { void* vtable[16]; };
class CHostStateMgr : CTier4AppSystem<IHostStateMgr,0>, ISwitchLoopModeStatusNotify { void* vtable[25]; };
class CHostStateMgr : ISwitchLoopModeStatusNotify { void* vtable[1]; };
class CHostSubscribeForProfileEvents : IMatchEventsSink { void* vtable[1]; };
class CInputService : CBaseEngineService<IInputService>, IInputHandler { void* vtable[62]; };
class CInputService : IInputHandler { void* vtable[1]; };
class CInstantReplay : IDemoPlayer, IInstantReplayIntercept { void* vtable[42]; };
class CInstantReplay : IInstantReplayIntercept { void* vtable[3]; };
class CKV3TransferContextBase : IErrorListener { void* vtable[6]; };
class CKV3TransferLoadContext : CKV3TransferContextBase { void* vtable[6]; };
class CKV3TransferSaveContext : CKV3TransferContextBase { void* vtable[6]; };
class CKeyValueCache : CTier4AppSystem<IKeyValueCache,0> { void* vtable[17]; };
class CLoadAutoCompletionFunctor : ICommandCallback, ICommandCompletionCallback { void* vtable[1]; };
class CLoadAutoCompletionFunctor : ICommandCompletionCallback { void* vtable[1]; };
class CLoadSpawnGroupsPrerequisite : IPrerequisite { void* vtable[6]; };
class CLoadStartupResourcePrerequisite : CGameResourceManifestPrerequisite, ILoopModePrerequisiteRegistry { void* vtable[7]; };
class CLoadStartupResourcePrerequisite : ILoopModePrerequisiteRegistry { void* vtable[2]; };
class CLoopModeAddonDownload : CLoopModeBase { void* vtable[8]; };
class CLoopModeConsole : CLoopModeBase { void* vtable[8]; };
class CLoopModeFactory<class CLoopModeAddonDownload> : ILoopModeFactory { void* vtable[5]; };
class CLoopModeFactory<class CLoopModeConsole> : ILoopModeFactory { void* vtable[5]; };
class CLoopModeFactory<class CLoopModeInGameUI> : ILoopModeFactory { void* vtable[5]; };
class CLoopModeFactory<class CLoopModeLevelLoad> : ILoopModeFactory { void* vtable[5]; };
class CLoopModeFactory<class CLoopModeMainMenu> : ILoopModeFactory { void* vtable[5]; };
class CLoopModeFactory<class CLoopModeRemoteConnect> : ILoopModeFactory { void* vtable[5]; };
class CLoopModeFactory<class CLoopModeSourceTVRelay> : ILoopModeFactory { void* vtable[5]; };
class CLoopModeInGameUI : CLoopModeBase { void* vtable[8]; };
class CLoopModeLevelLoad : CLoopModeBase { void* vtable[8]; };
class CLoopModeMainMenu : CLoopModeBase { void* vtable[8]; };
class CLoopModeRemoteConnect : CLoopModeBase { void* vtable[8]; };
class CLoopModeSourceTVRelay : CLoopModeBase { void* vtable[8]; };
class CLoopTypeBase : ILoopType { void* vtable[14]; };
class CLoopTypeClientServer : CLoopTypeBase { void* vtable[14]; };
class CLoopTypeClientServerService : CBaseEngineService<IEngineService>, IInputHandler, IRenderHandler { void* vtable[23]; };
class CLoopTypeClientServerService : IRenderHandler { void* vtable[3]; };
class CLoopTypeClientServerService : IInputHandler { void* vtable[1]; };
class CLoopTypeSimple : CLoopTypeBase { void* vtable[14]; };
class CLoopTypeSimpleService : CBaseEngineService<IEngineService>, IInputHandler, IRenderHandler { void* vtable[23]; };
class CLoopTypeSimpleService : IRenderHandler { void* vtable[3]; };
class CLoopTypeSimpleService : IInputHandler { void* vtable[1]; };
class CMapListService : CBaseEngineService<IMapListService> { void* vtable[26]; };
class CMaterialSystem2AppSystemDict : CTier2AppSystemDict, IRenderDeviceSetup { void* vtable[7]; };
class CMaterialSystem2AppSystemDict : IRenderDeviceSetup { void* vtable[1]; };
class CMetaDuplicationAutoCompletionFunctor : CEntityMETAAutoCompletionFunctor, ICommandCallback { void* vtable[1]; };
class CMetaDuplicationAutoCompletionFunctor : ICommandCallback { void* vtable[1]; };
class CMiniDumpCommentConvarsWriter : IPrintChangedConvarsWriter { void* vtable[2]; };
class CModuleMetadataProvider_ResourceManifests : CBaseVModuleMetadataProvider { void* vtable[1]; };
class CMovieRecorder : IMovieRecorder, IScreenshotCallback, IAudioStreamRecorder { void* vtable[15]; };
class CMovieRecorder : IScreenshotCallback { void* vtable[5]; };
class CMovieRecorder : IAudioStreamRecorder { void* vtable[3]; };
class CMsgConvarsWriter : IPrintChangedConvarsWriter { void* vtable[2]; };
class CMsgIPCAddress : google::protobuf::Message { void* vtable[17]; };
class CMsgPlayerInfo : google::protobuf::Message { void* vtable[17]; };
class CMsgQAngle : google::protobuf::Message { void* vtable[17]; };
class CMsgQuaternion : google::protobuf::Message { void* vtable[17]; };
class CMsgRGBA : google::protobuf::Message { void* vtable[17]; };
class CMsgServerNetworkStats : google::protobuf::Message { void* vtable[17]; };
class CMsgServerNetworkStats_Player : google::protobuf::Message { void* vtable[17]; };
class CMsgServerNetworkStats_Port : google::protobuf::Message { void* vtable[17]; };
class CMsgServerPeer : google::protobuf::Message { void* vtable[17]; };
class CMsgServerUserCmd : google::protobuf::Message { void* vtable[17]; };
class CMsgSource2NetworkFlowQuality : google::protobuf::Message { void* vtable[17]; };
class CMsgSource2PerfIntervalSample : google::protobuf::Message { void* vtable[17]; };
class CMsgSource2PerfIntervalSample_Tag : google::protobuf::Message { void* vtable[17]; };
class CMsgSource2PlayStatsPackedRecordList : google::protobuf::Message { void* vtable[17]; };
class CMsgSource2PlayStatsPackedRecordList_FieldDef : google::protobuf::Message { void* vtable[17]; };
class CMsgSource2SystemSpecs : google::protobuf::Message { void* vtable[17]; };
class CMsgSource2VProfLiteReport : google::protobuf::Message { void* vtable[17]; };
class CMsgSource2VProfLiteReportItem : google::protobuf::Message { void* vtable[17]; };
class CMsgTransform : google::protobuf::Message { void* vtable[17]; };
class CMsgVector : google::protobuf::Message { void* vtable[17]; };
class CMsgVector2D : google::protobuf::Message { void* vtable[17]; };
class CMsgVoiceAudio : google::protobuf::Message { void* vtable[17]; };
class CMsg_CVars : google::protobuf::Message { void* vtable[17]; };
class CMsg_CVars_CVar : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_DebugOverlay : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_DebugOverlay_t : CNETMsg_DebugOverlay { void* vtable[17]; };
class CNETMsg_DebugOverlay_t : CNetMessagePB<15,CNETMsg_DebugOverlay,16,1,0>, CNETMsg_DebugOverlay { void* vtable[5]; };
class CNETMsg_NOP : google::protobuf::internal::ZeroFieldsBase { void* vtable[17]; };
class CNETMsg_SetConVar : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_SetConVar_t : CNETMsg_SetConVar { void* vtable[17]; };
class CNETMsg_SetConVar_t : CNetMessagePB<6,CNETMsg_SetConVar,9,1,0>, CNETMsg_SetConVar { void* vtable[5]; };
class CNETMsg_SignonState : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_SignonState_t : CNETMsg_SignonState { void* vtable[17]; };
class CNETMsg_SignonState_t : CNetMessagePB<7,CNETMsg_SignonState,10,1,0>, CNETMsg_SignonState { void* vtable[5]; };
class CNETMsg_SpawnGroup_Load : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_SpawnGroup_LoadCompleted : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_SpawnGroup_LoadCompleted_t : CNETMsg_SpawnGroup_LoadCompleted { void* vtable[17]; };
class CNETMsg_SpawnGroup_LoadCompleted_t : CNetMessagePB<13,CNETMsg_SpawnGroup_LoadCompleted,15,1,0>, CNETMsg_SpawnGroup_LoadCompleted { void* vtable[5]; };
class CNETMsg_SpawnGroup_Load_t : CNETMsg_SpawnGroup_Load { void* vtable[17]; };
class CNETMsg_SpawnGroup_Load_t : CNetMessagePB<8,CNETMsg_SpawnGroup_Load,15,1,0>, CNETMsg_SpawnGroup_Load { void* vtable[5]; };
class CNETMsg_SpawnGroup_ManifestUpdate : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_SpawnGroup_ManifestUpdate_t : CNETMsg_SpawnGroup_ManifestUpdate { void* vtable[17]; };
class CNETMsg_SpawnGroup_ManifestUpdate_t : CNetMessagePB<9,CNETMsg_SpawnGroup_ManifestUpdate,15,1,0>, CNETMsg_SpawnGroup_ManifestUpdate { void* vtable[5]; };
class CNETMsg_SpawnGroup_SetCreationTick : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_SpawnGroup_SetCreationTick_t : CNETMsg_SpawnGroup_SetCreationTick { void* vtable[17]; };
class CNETMsg_SpawnGroup_SetCreationTick_t : CNetMessagePB<11,CNETMsg_SpawnGroup_SetCreationTick,15,1,0>, CNETMsg_SpawnGroup_SetCreationTick { void* vtable[5]; };
class CNETMsg_SpawnGroup_Unload : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_SpawnGroup_Unload_t : CNETMsg_SpawnGroup_Unload { void* vtable[17]; };
class CNETMsg_SpawnGroup_Unload_t : CNetMessagePB<12,CNETMsg_SpawnGroup_Unload,15,1,0>, CNETMsg_SpawnGroup_Unload { void* vtable[5]; };
class CNETMsg_SplitScreenUser : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_StringCmd : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_StringCmd_t : CNETMsg_StringCmd { void* vtable[17]; };
class CNETMsg_StringCmd_t : CNetMessagePB<5,CNETMsg_StringCmd,9,1,0>, CNETMsg_StringCmd { void* vtable[5]; };
class CNETMsg_Tick : google::protobuf::Message { void* vtable[17]; };
class CNETMsg_Tick_t : CNETMsg_Tick { void* vtable[17]; };
class CNETMsg_Tick_t : CNetMessagePB<4,CNETMsg_Tick,16,0,0>, CNETMsg_Tick { void* vtable[5]; };
class CNetConsoleMgr : ISocketCreatorListener { void* vtable[3]; };
class CNetMessage { void* vtable[5]; };
class CNetMessagePB<-1,class C2S_CONNECTION_Message,0,1,0> : C2S_CONNECTION_Message { void* vtable[17]; };
class CNetMessagePB<-1,class C2S_CONNECTION_Message,0,1,0> : CNetMessage, C2S_CONNECTION_Message { void* vtable[5]; };
class CNetMessagePB<-1,class C2S_CONNECTION_Message,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<-1,class C2S_CONNECT_Message,0,1,0> : C2S_CONNECT_Message { void* vtable[17]; };
class CNetMessagePB<-1,class C2S_CONNECT_Message,0,1,0> : CNetMessage, C2S_CONNECT_Message { void* vtable[5]; };
class CNetMessagePB<-1,class C2S_CONNECT_Message,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<-1,class NetMessageConnectionClosed,11,1,0> : NetMessageConnectionClosed { void* vtable[17]; };
class CNetMessagePB<-1,class NetMessageConnectionClosed,11,1,0> : CNetMessage, NetMessageConnectionClosed { void* vtable[5]; };
class CNetMessagePB<-1,class NetMessageConnectionClosed,11,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<-1,class NetMessageConnectionCrashed,11,1,0> : NetMessageConnectionCrashed { void* vtable[17]; };
class CNetMessagePB<-1,class NetMessageConnectionCrashed,11,1,0> : CNetMessage, NetMessageConnectionCrashed { void* vtable[5]; };
class CNetMessagePB<-1,class NetMessageConnectionCrashed,11,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<-1,class NetMessageSplitscreenUserChanged,11,1,0> : NetMessageSplitscreenUserChanged { void* vtable[17]; };
class CNetMessagePB<-1,class NetMessageSplitscreenUserChanged,11,1,0> : CNetMessage, NetMessageSplitscreenUserChanged { void* vtable[5]; };
class CNetMessagePB<-1,class NetMessageSplitscreenUserChanged,11,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<1073741824,class NetMessagePacketStart,11,1,0> : NetMessagePacketStart { void* vtable[17]; };
class CNetMessagePB<1073741824,class NetMessagePacketStart,11,1,0> : CNetMessage, NetMessagePacketStart { void* vtable[5]; };
class CNetMessagePB<1073741824,class NetMessagePacketStart,11,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<1073741825,class NetMessagePacketEnd,11,1,0> : NetMessagePacketEnd { void* vtable[17]; };
class CNetMessagePB<1073741825,class NetMessagePacketEnd,11,1,0> : CNetMessage, NetMessagePacketEnd { void* vtable[5]; };
class CNetMessagePB<1073741825,class NetMessagePacketEnd,11,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<11,class CNETMsg_SpawnGroup_SetCreationTick,15,1,0> : CNETMsg_SpawnGroup_SetCreationTick { void* vtable[17]; };
class CNetMessagePB<11,class CNETMsg_SpawnGroup_SetCreationTick,15,1,0> : CNetMessage, CNETMsg_SpawnGroup_SetCreationTick { void* vtable[5]; };
class CNetMessagePB<11,class CNETMsg_SpawnGroup_SetCreationTick,15,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<12,class CNETMsg_SpawnGroup_Unload,15,1,0> : CNETMsg_SpawnGroup_Unload { void* vtable[17]; };
class CNetMessagePB<12,class CNETMsg_SpawnGroup_Unload,15,1,0> : CNetMessage, CNETMsg_SpawnGroup_Unload { void* vtable[5]; };
class CNetMessagePB<12,class CNETMsg_SpawnGroup_Unload,15,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<13,class CNETMsg_SpawnGroup_LoadCompleted,15,1,0> : CNETMsg_SpawnGroup_LoadCompleted { void* vtable[17]; };
class CNetMessagePB<13,class CNETMsg_SpawnGroup_LoadCompleted,15,1,0> : CNetMessage, CNETMsg_SpawnGroup_LoadCompleted { void* vtable[5]; };
class CNetMessagePB<13,class CNETMsg_SpawnGroup_LoadCompleted,15,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<15,class CNETMsg_DebugOverlay,16,1,0> : CNETMsg_DebugOverlay { void* vtable[17]; };
class CNetMessagePB<15,class CNETMsg_DebugOverlay,16,1,0> : CNetMessage, CNETMsg_DebugOverlay { void* vtable[5]; };
class CNetMessagePB<15,class CNETMsg_DebugOverlay,16,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<16,class CBidirMsg_RebroadcastGameEvent,5,1,1> : CBidirMsg_RebroadcastGameEvent { void* vtable[17]; };
class CNetMessagePB<16,class CBidirMsg_RebroadcastGameEvent,5,1,1> : CNetMessage, CBidirMsg_RebroadcastGameEvent { void* vtable[5]; };
class CNetMessagePB<16,class CBidirMsg_RebroadcastGameEvent,5,1,1>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<17,class CBidirMsg_RebroadcastSource,5,1,1> : CBidirMsg_RebroadcastSource { void* vtable[17]; };
class CNetMessagePB<17,class CBidirMsg_RebroadcastSource,5,1,1> : CNetMessage, CBidirMsg_RebroadcastSource { void* vtable[5]; };
class CNetMessagePB<17,class CBidirMsg_RebroadcastSource,5,1,1>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<19,class CBidirMsg_PredictionEvent,0,0,0> : CBidirMsg_PredictionEvent { void* vtable[17]; };
class CNetMessagePB<19,class CBidirMsg_PredictionEvent,0,0,0> : CNetMessage, CBidirMsg_PredictionEvent { void* vtable[5]; };
class CNetMessagePB<19,class CBidirMsg_PredictionEvent,0,0,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<20,class CCLCMsg_ClientInfo,10,1,0> : CCLCMsg_ClientInfo { void* vtable[17]; };
class CNetMessagePB<20,class CCLCMsg_ClientInfo,10,1,0> : CNetMessage, CCLCMsg_ClientInfo { void* vtable[5]; };
class CNetMessagePB<20,class CCLCMsg_ClientInfo,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<21,class CCLCMsg_Move,8,0,0> : CCLCMsg_Move { void* vtable[17]; };
class CNetMessagePB<21,class CCLCMsg_Move,8,0,0> : CNetMessage, CCLCMsg_Move { void* vtable[5]; };
class CNetMessagePB<21,class CCLCMsg_Move,8,0,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<22,class CCLCMsg_VoiceData,6,0,0> : CCLCMsg_VoiceData { void* vtable[17]; };
class CNetMessagePB<22,class CCLCMsg_VoiceData,6,0,0> : CNetMessage, CCLCMsg_VoiceData { void* vtable[5]; };
class CNetMessagePB<22,class CCLCMsg_VoiceData,6,0,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<23,class CCLCMsg_BaselineAck,16,1,0> : CCLCMsg_BaselineAck { void* vtable[17]; };
class CNetMessagePB<23,class CCLCMsg_BaselineAck,16,1,0> : CNetMessage, CCLCMsg_BaselineAck { void* vtable[5]; };
class CNetMessagePB<23,class CCLCMsg_BaselineAck,16,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<25,class CCLCMsg_RespondCvarValue,0,1,0> : CCLCMsg_RespondCvarValue { void* vtable[17]; };
class CNetMessagePB<25,class CCLCMsg_RespondCvarValue,0,1,0> : CNetMessage, CCLCMsg_RespondCvarValue { void* vtable[5]; };
class CNetMessagePB<25,class CCLCMsg_RespondCvarValue,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<27,class CCLCMsg_LoadingProgress,10,1,0> : CCLCMsg_LoadingProgress { void* vtable[17]; };
class CNetMessagePB<27,class CCLCMsg_LoadingProgress,10,1,0> : CNetMessage, CCLCMsg_LoadingProgress { void* vtable[5]; };
class CNetMessagePB<27,class CCLCMsg_LoadingProgress,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<28,class CCLCMsg_SplitPlayerConnect,10,1,0> : CCLCMsg_SplitPlayerConnect { void* vtable[17]; };
class CNetMessagePB<28,class CCLCMsg_SplitPlayerConnect,10,1,0> : CNetMessage, CCLCMsg_SplitPlayerConnect { void* vtable[5]; };
class CNetMessagePB<28,class CCLCMsg_SplitPlayerConnect,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<30,class CCLCMsg_SplitPlayerDisconnect,10,1,0> : CCLCMsg_SplitPlayerDisconnect { void* vtable[17]; };
class CNetMessagePB<30,class CCLCMsg_SplitPlayerDisconnect,10,1,0> : CNetMessage, CCLCMsg_SplitPlayerDisconnect { void* vtable[5]; };
class CNetMessagePB<30,class CCLCMsg_SplitPlayerDisconnect,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<31,class CCLCMsg_ServerStatus,0,1,0> : CCLCMsg_ServerStatus { void* vtable[17]; };
class CNetMessagePB<31,class CCLCMsg_ServerStatus,0,1,0> : CNetMessage, CCLCMsg_ServerStatus { void* vtable[5]; };
class CNetMessagePB<31,class CCLCMsg_ServerStatus,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<33,class CCLCMsg_RequestPause,0,1,0> : CCLCMsg_RequestPause { void* vtable[17]; };
class CNetMessagePB<33,class CCLCMsg_RequestPause,0,1,0> : CNetMessage, CCLCMsg_RequestPause { void* vtable[5]; };
class CNetMessagePB<33,class CCLCMsg_RequestPause,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<34,class CBaseCmdKeyValues<class CCLCMsg_CmdKeyValues>,9,1,0> : CBaseCmdKeyValues<CCLCMsg_CmdKeyValues> { void* vtable[17]; };
class CNetMessagePB<34,class CBaseCmdKeyValues<class CCLCMsg_CmdKeyValues>,9,1,0> : CNetMessage, CBaseCmdKeyValues<CCLCMsg_CmdKeyValues> { void* vtable[5]; };
class CNetMessagePB<34,class CBaseCmdKeyValues<class CCLCMsg_CmdKeyValues>,9,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<35,class CCLCMsg_RconServerDetails,0,1,0> : CCLCMsg_RconServerDetails { void* vtable[17]; };
class CNetMessagePB<35,class CCLCMsg_RconServerDetails,0,1,0> : CNetMessage, CCLCMsg_RconServerDetails { void* vtable[5]; };
class CNetMessagePB<35,class CCLCMsg_RconServerDetails,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<36,class CCLCMsg_HltvReplay,17,1,0> : CCLCMsg_HltvReplay { void* vtable[17]; };
class CNetMessagePB<36,class CCLCMsg_HltvReplay,17,1,0> : CNetMessage, CCLCMsg_HltvReplay { void* vtable[5]; };
class CNetMessagePB<36,class CCLCMsg_HltvReplay,17,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<37,class CCLCMsg_Diagnostic,0,1,0> : CCLCMsg_Diagnostic { void* vtable[17]; };
class CNetMessagePB<37,class CCLCMsg_Diagnostic,0,1,0> : CNetMessage, CCLCMsg_Diagnostic { void* vtable[5]; };
class CNetMessagePB<37,class CCLCMsg_Diagnostic,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<4,class CNETMsg_Tick,16,0,0> : CNETMsg_Tick { void* vtable[17]; };
class CNetMessagePB<4,class CNETMsg_Tick,16,0,0> : CNetMessage, CNETMsg_Tick { void* vtable[5]; };
class CNetMessagePB<4,class CNETMsg_Tick,16,0,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<40,class CSVCMsg_ServerInfo,10,1,0> : CSVCMsg_ServerInfo { void* vtable[17]; };
class CNetMessagePB<40,class CSVCMsg_ServerInfo,10,1,0> : CNetMessage, CSVCMsg_ServerInfo { void* vtable[5]; };
class CNetMessagePB<40,class CSVCMsg_ServerInfo,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<41,class CSVCMsg_FlattenedSerializerWrapper,10,1,0> : CSVCMsg_FlattenedSerializerWrapper { void* vtable[17]; };
class CNetMessagePB<41,class CSVCMsg_FlattenedSerializerWrapper,10,1,0> : CNetMessage, CSVCMsg_FlattenedSerializerWrapper { void* vtable[5]; };
class CNetMessagePB<41,class CSVCMsg_FlattenedSerializerWrapper,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<42,class CSVCMsg_ClassInfo,10,1,0> : CSVCMsg_ClassInfo { void* vtable[17]; };
class CNetMessagePB<42,class CSVCMsg_ClassInfo,10,1,0> : CNetMessage, CSVCMsg_ClassInfo { void* vtable[5]; };
class CNetMessagePB<42,class CSVCMsg_ClassInfo,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<43,class CSVCMsg_SetPause,0,1,0> : CSVCMsg_SetPause { void* vtable[17]; };
class CNetMessagePB<43,class CSVCMsg_SetPause,0,1,0> : CNetMessage, CSVCMsg_SetPause { void* vtable[5]; };
class CNetMessagePB<43,class CSVCMsg_SetPause,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<44,class CSVCMsg_CreateStringTable,10,1,0> : CSVCMsg_CreateStringTable { void* vtable[17]; };
class CNetMessagePB<44,class CSVCMsg_CreateStringTable,10,1,0> : CNetMessage, CSVCMsg_CreateStringTable { void* vtable[5]; };
class CNetMessagePB<44,class CSVCMsg_CreateStringTable,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<45,class CSVCMsg_UpdateStringTable,7,1,0> : CSVCMsg_UpdateStringTable { void* vtable[17]; };
class CNetMessagePB<45,class CSVCMsg_UpdateStringTable,7,1,0> : CNetMessage, CSVCMsg_UpdateStringTable { void* vtable[5]; };
class CNetMessagePB<45,class CSVCMsg_UpdateStringTable,7,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<46,class CSVCMsg_VoiceInit,10,1,0> : CSVCMsg_VoiceInit { void* vtable[17]; };
class CNetMessagePB<46,class CSVCMsg_VoiceInit,10,1,0> : CNetMessage, CSVCMsg_VoiceInit { void* vtable[5]; };
class CNetMessagePB<46,class CSVCMsg_VoiceInit,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<47,class CSVCMsg_VoiceData,6,0,0> : CSVCMsg_VoiceData { void* vtable[17]; };
class CNetMessagePB<47,class CSVCMsg_VoiceData,6,0,0> : CNetMessage, CSVCMsg_VoiceData { void* vtable[5]; };
class CNetMessagePB<47,class CSVCMsg_VoiceData,6,0,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<48,class CSVCMsg_Print,0,1,0> : CSVCMsg_Print { void* vtable[17]; };
class CNetMessagePB<48,class CSVCMsg_Print,0,1,0> : CNetMessage, CSVCMsg_Print { void* vtable[5]; };
class CNetMessagePB<48,class CSVCMsg_Print,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<49,class CSVCMsg_Sounds,4,1,0> : CSVCMsg_Sounds { void* vtable[17]; };
class CNetMessagePB<49,class CSVCMsg_Sounds,4,1,0> : CNetMessage, CSVCMsg_Sounds { void* vtable[5]; };
class CNetMessagePB<49,class CSVCMsg_Sounds,4,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<5,class CNETMsg_StringCmd,9,1,0> : CNETMsg_StringCmd { void* vtable[17]; };
class CNetMessagePB<5,class CNETMsg_StringCmd,9,1,0> : CNetMessage, CNETMsg_StringCmd { void* vtable[5]; };
class CNetMessagePB<5,class CNETMsg_StringCmd,9,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<50,class CSVCMsg_SetView,0,1,0> : CSVCMsg_SetView { void* vtable[17]; };
class CNetMessagePB<50,class CSVCMsg_SetView,0,1,0> : CNetMessage, CSVCMsg_SetView { void* vtable[5]; };
class CNetMessagePB<50,class CSVCMsg_SetView,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<51,class CSVCMsg_ClearAllStringTables,10,1,0> : CSVCMsg_ClearAllStringTables { void* vtable[17]; };
class CNetMessagePB<51,class CSVCMsg_ClearAllStringTables,10,1,0> : CNetMessage, CSVCMsg_ClearAllStringTables { void* vtable[5]; };
class CNetMessagePB<51,class CSVCMsg_ClearAllStringTables,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<52,class CBaseCmdKeyValues<class CSVCMsg_CmdKeyValues>,9,1,0> : CBaseCmdKeyValues<CSVCMsg_CmdKeyValues> { void* vtable[17]; };
class CNetMessagePB<52,class CBaseCmdKeyValues<class CSVCMsg_CmdKeyValues>,9,1,0> : CNetMessage, CBaseCmdKeyValues<CSVCMsg_CmdKeyValues> { void* vtable[5]; };
class CNetMessagePB<52,class CBaseCmdKeyValues<class CSVCMsg_CmdKeyValues>,9,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<54,class CSVCMsg_SplitScreen,10,1,0> : CSVCMsg_SplitScreen { void* vtable[17]; };
class CNetMessagePB<54,class CSVCMsg_SplitScreen,10,1,0> : CNetMessage, CSVCMsg_SplitScreen { void* vtable[5]; };
class CNetMessagePB<54,class CSVCMsg_SplitScreen,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<55,class CSVCMsg_PacketEntities,-1,1,0> : CSVCMsg_PacketEntities { void* vtable[17]; };
class CNetMessagePB<55,class CSVCMsg_PacketEntities,-1,1,0> : CNetMessage, CSVCMsg_PacketEntities { void* vtable[5]; };
class CNetMessagePB<55,class CSVCMsg_PacketEntities,-1,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<56,class CSVCMsg_Prefetch,4,1,0> : CSVCMsg_Prefetch { void* vtable[17]; };
class CNetMessagePB<56,class CSVCMsg_Prefetch,4,1,0> : CNetMessage, CSVCMsg_Prefetch { void* vtable[5]; };
class CNetMessagePB<56,class CSVCMsg_Prefetch,4,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<57,class CSVCMsg_Menu,0,1,0> : CSVCMsg_Menu { void* vtable[17]; };
class CNetMessagePB<57,class CSVCMsg_Menu,0,1,0> : CNetMessage, CSVCMsg_Menu { void* vtable[5]; };
class CNetMessagePB<57,class CSVCMsg_Menu,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<58,class CSVCMsg_GetCvarValue,0,1,0> : CSVCMsg_GetCvarValue { void* vtable[17]; };
class CNetMessagePB<58,class CSVCMsg_GetCvarValue,0,1,0> : CNetMessage, CSVCMsg_GetCvarValue { void* vtable[5]; };
class CNetMessagePB<58,class CSVCMsg_GetCvarValue,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<59,class CSVCMsg_StopSound,4,1,0> : CSVCMsg_StopSound { void* vtable[17]; };
class CNetMessagePB<59,class CSVCMsg_StopSound,4,1,0> : CNetMessage, CSVCMsg_StopSound { void* vtable[5]; };
class CNetMessagePB<59,class CSVCMsg_StopSound,4,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<6,class CNETMsg_SetConVar,9,1,0> : CNETMsg_SetConVar { void* vtable[17]; };
class CNetMessagePB<6,class CNETMsg_SetConVar,9,1,0> : CNetMessage, CNETMsg_SetConVar { void* vtable[5]; };
class CNetMessagePB<6,class CNETMsg_SetConVar,9,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<60,class CSVCMsg_PeerList,0,1,0> : CSVCMsg_PeerList { void* vtable[17]; };
class CNetMessagePB<60,class CSVCMsg_PeerList,0,1,0> : CNetMessage, CSVCMsg_PeerList { void* vtable[5]; };
class CNetMessagePB<60,class CSVCMsg_PeerList,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<61,class CSVCMsg_PacketReliable,0,1,0> : CSVCMsg_PacketReliable { void* vtable[17]; };
class CNetMessagePB<61,class CSVCMsg_PacketReliable,0,1,0> : CNetMessage, CSVCMsg_PacketReliable { void* vtable[5]; };
class CNetMessagePB<61,class CSVCMsg_PacketReliable,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<62,class CSVCMsg_HLTVStatus,0,1,1> : CSVCMsg_HLTVStatus { void* vtable[17]; };
class CNetMessagePB<62,class CSVCMsg_HLTVStatus,0,1,1> : CNetMessage, CSVCMsg_HLTVStatus { void* vtable[5]; };
class CNetMessagePB<62,class CSVCMsg_HLTVStatus,0,1,1>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<63,class CSVCMsg_ServerSteamID,0,1,1> : CSVCMsg_ServerSteamID { void* vtable[17]; };
class CNetMessagePB<63,class CSVCMsg_ServerSteamID,0,1,1> : CNetMessage, CSVCMsg_ServerSteamID { void* vtable[5]; };
class CNetMessagePB<63,class CSVCMsg_ServerSteamID,0,1,1>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<7,class CNETMsg_SignonState,10,1,0> : CNETMsg_SignonState { void* vtable[17]; };
class CNetMessagePB<7,class CNETMsg_SignonState,10,1,0> : CNetMessage, CNETMsg_SignonState { void* vtable[5]; };
class CNetMessagePB<7,class CNETMsg_SignonState,10,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<70,class CSVCMsg_FullFrameSplit,0,1,0> : CSVCMsg_FullFrameSplit { void* vtable[17]; };
class CNetMessagePB<70,class CSVCMsg_FullFrameSplit,0,1,0> : CNetMessage, CSVCMsg_FullFrameSplit { void* vtable[5]; };
class CNetMessagePB<70,class CSVCMsg_FullFrameSplit,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<71,class CSVCMsg_RconServerDetails,0,1,0> : CSVCMsg_RconServerDetails { void* vtable[17]; };
class CNetMessagePB<71,class CSVCMsg_RconServerDetails,0,1,0> : CNetMessage, CSVCMsg_RconServerDetails { void* vtable[5]; };
class CNetMessagePB<71,class CSVCMsg_RconServerDetails,0,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<72,class CSVCMsg_UserMessage,13,1,0> : CSVCMsg_UserMessage { void* vtable[17]; };
class CNetMessagePB<72,class CSVCMsg_UserMessage,13,1,0> : CNetMessage, CSVCMsg_UserMessage { void* vtable[5]; };
class CNetMessagePB<72,class CSVCMsg_UserMessage,13,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<74,class CSVCMsg_HltvReplay,17,1,0> : CSVCMsg_HltvReplay { void* vtable[17]; };
class CNetMessagePB<74,class CSVCMsg_HltvReplay,17,1,0> : CNetMessage, CSVCMsg_HltvReplay { void* vtable[5]; };
class CNetMessagePB<74,class CSVCMsg_HltvReplay,17,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<75,class CCLCMsg_HltvFixupOperatorTick,17,1,0> : CCLCMsg_HltvFixupOperatorTick { void* vtable[17]; };
class CNetMessagePB<75,class CCLCMsg_HltvFixupOperatorTick,17,1,0> : CNetMessage, CCLCMsg_HltvFixupOperatorTick { void* vtable[5]; };
class CNetMessagePB<75,class CCLCMsg_HltvFixupOperatorTick,17,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<76,class CSVCMsg_UserCommands,17,1,0> : CSVCMsg_UserCommands { void* vtable[17]; };
class CNetMessagePB<76,class CSVCMsg_UserCommands,17,1,0> : CNetMessage, CSVCMsg_UserCommands { void* vtable[5]; };
class CNetMessagePB<76,class CSVCMsg_UserCommands,17,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<77,class CSVCMsg_NextMsgPredicted,17,1,0> : CSVCMsg_NextMsgPredicted { void* vtable[17]; };
class CNetMessagePB<77,class CSVCMsg_NextMsgPredicted,17,1,0> : CNetMessage, CSVCMsg_NextMsgPredicted { void* vtable[5]; };
class CNetMessagePB<77,class CSVCMsg_NextMsgPredicted,17,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<8,class CNETMsg_SpawnGroup_Load,15,1,0> : CNETMsg_SpawnGroup_Load { void* vtable[17]; };
class CNetMessagePB<8,class CNETMsg_SpawnGroup_Load,15,1,0> : CNetMessage, CNETMsg_SpawnGroup_Load { void* vtable[5]; };
class CNetMessagePB<8,class CNETMsg_SpawnGroup_Load,15,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetMessagePB<9,class CNETMsg_SpawnGroup_ManifestUpdate,15,1,0> : CNETMsg_SpawnGroup_ManifestUpdate { void* vtable[17]; };
class CNetMessagePB<9,class CNETMsg_SpawnGroup_ManifestUpdate,15,1,0> : CNetMessage, CNETMsg_SpawnGroup_ManifestUpdate { void* vtable[5]; };
class CNetMessagePB<9,class CNETMsg_SpawnGroup_ManifestUpdate,15,1,0>::CProtobufBinding : IProtobufBinding { void* vtable[9]; };
class CNetSupportImpl : CBaseAppSystem<INetSupport> { void* vtable[22]; };
class CNetworkClientService : CBaseEngineService<INetworkClientService>, CUtlSlot, IVConCommDataReceived { void* vtable[64]; };
class CNetworkClientService : IVConCommDataReceived { void* vtable[1]; };
class CNetworkClientSpawnGroup : CBaseSpawnGroup, IComputeWorldOriginCallback, IGameResourceManifestLoadCompletionCallback { void* vtable[45]; };
class CNetworkClientSpawnGroup : IGameResourceManifestLoadCompletionCallback { void* vtable[2]; };
class CNetworkClientSpawnGroup : IComputeWorldOriginCallback { void* vtable[1]; };
class CNetworkClientSpawnGroupCreatePrerequisites : CSequentialPrerequisite, IPrerequisiteRegistry { void* vtable[8]; };
class CNetworkClientSpawnGroupCreatePrerequisites : IPrerequisiteRegistry { void* vtable[2]; };
class CNetworkClientSpawnGroup_AllocateEntitiesPrerequisite : CBaseClientSpawnGroupCreatePrerequisite { void* vtable[6]; };
class CNetworkClientSpawnGroup_AllocateSpawnGroupPrerequisite : CBaseClientSpawnGroupCreatePrerequisite { void* vtable[6]; };
class CNetworkClientSpawnGroup_LoadEntitiesPrerequisite : CBaseClientSpawnGroupCreatePrerequisite { void* vtable[6]; };
class CNetworkClientSpawnGroup_LoadPreviousLevelPrerequisite : CNetworkClientSpawnGroup_LoadSaveGamePrerequisiteBase { void* vtable[8]; };
class CNetworkClientSpawnGroup_LoadSaveGamePrerequisite : CNetworkClientSpawnGroup_LoadSaveGamePrerequisiteBase { void* vtable[8]; };
class CNetworkClientSpawnGroup_LoadSaveGamePrerequisiteBase : CBaseClientSpawnGroupCreatePrerequisite { void* vtable[8]; };
class CNetworkClientSpawnGroup_WaitForAssetLoadPrerequisite : CBaseClientSpawnGroupCreatePrerequisite, ISpawnGroupPrerequisiteRegistry { void* vtable[6]; };
class CNetworkClientSpawnGroup_WaitForAssetLoadPrerequisite : ISpawnGroupPrerequisiteRegistry { void* vtable[2]; };
class CNetworkClientSpawnGroup_WaitForChildSpawnGroups : CBaseClientSpawnGroupCreatePrerequisite { void* vtable[6]; };
class CNetworkClientSpawnGroup_WaitForOwnerSpawnGroupPrerequisite : CBaseClientSpawnGroupCreatePrerequisite { void* vtable[6]; };
class CNetworkGameClient : CNetworkGameClientBase, CUtlSlot, INetworkMessageProcessingPreFilter, IConnectionlessPacketHandler, INetworkChannelNotify, IGameEventWatcher, ISwitchLoopModeStatusNotify { void* vtable[142]; };
class CNetworkGameClient : IConnectionlessPacketHandler { void* vtable[2]; };
class CNetworkGameClient : IGameEventWatcher { void* vtable[1]; };
class CNetworkGameClient : INetworkChannelNotify { void* vtable[1]; };
class CNetworkGameClient : INetworkMessageProcessingPreFilter { void* vtable[1]; };
class CNetworkGameClient : ISwitchLoopModeStatusNotify { void* vtable[1]; };
class CNetworkGameClientBase : INetworkGameClient, CUtlSlot, INetworkMessageProcessingPreFilter, IConnectionlessPacketHandler, INetworkChannelNotify, IGameEventWatcher { void* vtable[142]; };
class CNetworkGameClientBase : IConnectionlessPacketHandler { void* vtable[2]; };
class CNetworkGameClientBase : IGameEventWatcher { void* vtable[1]; };
class CNetworkGameClientBase : INetworkChannelNotify { void* vtable[1]; };
class CNetworkGameClientBase : INetworkMessageProcessingPreFilter { void* vtable[1]; };
class CNetworkGameServer : CNetworkGameServerBase, IConnectionlessPacketHandler, IConVarListener { void* vtable[81]; };
class CNetworkGameServer : IConVarListener { void* vtable[2]; };
class CNetworkGameServer : IConnectionlessPacketHandler { void* vtable[2]; };
class CNetworkGameServerBase : INetworkGameServer, IConnectionlessPacketHandler, IConVarListener { void* vtable[81]; };
class CNetworkGameServerBase : IConVarListener { void* vtable[2]; };
class CNetworkGameServerBase : IConnectionlessPacketHandler { void* vtable[2]; };
class CNetworkP2PService : CBaseEngineService<INetworkP2PService>, CUtlSlot { void* vtable[33]; };
class CNetworkServerCreatePrerequisites : CSequentialPrerequisite, IPrerequisiteRegistry { void* vtable[8]; };
class CNetworkServerCreatePrerequisites : IPrerequisiteRegistry { void* vtable[2]; };
class CNetworkServerService : CBaseEngineService<INetworkServerService>, IVConCommDataReceived { void* vtable[51]; };
class CNetworkServerService : IVConCommDataReceived { void* vtable[1]; };
class CNetworkServerSpawnGroup : CBaseSpawnGroup, IComputeWorldOriginCallback, IGameResourceManifestLoadCompletionCallback { void* vtable[45]; };
class CNetworkServerSpawnGroup : IGameResourceManifestLoadCompletionCallback { void* vtable[2]; };
class CNetworkServerSpawnGroup : IComputeWorldOriginCallback { void* vtable[1]; };
class CNetworkServerSpawnGroupCreatePrerequisites : CSequentialPrerequisite, IPrerequisiteRegistry { void* vtable[8]; };
class CNetworkServerSpawnGroupCreatePrerequisites : IPrerequisiteRegistry { void* vtable[2]; };
class CNetworkServerSpawnGroup_AllocateEntitiesPrerequisite : CBaseServerSpawnGroupCreatePrerequisite { void* vtable[6]; };
class CNetworkServerSpawnGroup_AllocatePrerequisite : CBaseServerSpawnGroupCreatePrerequisite { void* vtable[6]; };
class CNetworkServerSpawnGroup_LoadEntitiesPrerequisite : CBaseServerSpawnGroupCreatePrerequisite { void* vtable[6]; };
class CNetworkServerSpawnGroup_LoadPreviousLevelPrerequisite : CNetworkServerSpawnGroup_LoadSaveGamePrerequisiteBase { void* vtable[9]; };
class CNetworkServerSpawnGroup_LoadSaveGamePrerequisite : CNetworkServerSpawnGroup_LoadSaveGamePrerequisiteBase { void* vtable[9]; };
class CNetworkServerSpawnGroup_LoadSaveGamePrerequisiteBase : CBaseServerSpawnGroupCreatePrerequisite { void* vtable[9]; };
class CNetworkServerSpawnGroup_WaitForAssetLoadPrerequisite : CBaseServerSpawnGroupCreatePrerequisite, ISpawnGroupPrerequisiteRegistry { void* vtable[6]; };
class CNetworkServerSpawnGroup_WaitForAssetLoadPrerequisite : ISpawnGroupPrerequisiteRegistry { void* vtable[2]; };
class CNetworkServerSpawnGroup_WaitForChildSpawnGroups : CBaseServerSpawnGroupCreatePrerequisite { void* vtable[6]; };
class CNetworkServerSpawnGroup_WaitForClients : CBaseServerSpawnGroupCreatePrerequisite { void* vtable[6]; };
class CNetworkServerSpawnGroup_WaitForOwnerSpawnGroupPrerequisite : CBaseServerSpawnGroupCreatePrerequisite { void* vtable[6]; };
class CNetworkService : CBaseEngineService<INetworkService> { void* vtable[24]; };
class CNetworkStringDict : INetworkStringDict { void* vtable[9]; };
class CNetworkStringTable : INetworkStringTable { void* vtable[17]; };
class CNetworkStringTableContainer : CTier4AppSystem<INetworkStringTableContainer,0> { void* vtable[18]; };
class COutOfPVSDeltaEntityHeaderWriter : CDeltaEntitysHeaderWriterBase { void* vtable[1]; };
class COutOfPVSDeltaEntitytHeaderReader : CDeltaEntityHeaderReaderBase { void* vtable[1]; };
class CP4File { void* vtable[11]; };
class CPVS : IPVS { void* vtable[32]; };
class CPanoramaInputHandler : CBaseGameUIInputHandler { void* vtable[2]; };
class CPanoramaProceduralLayer : IProceduralLayerRenderer { void* vtable[3]; };
class CParallelProcessorAbstract<class CParallelProcessor<CrashItem_t,class CFuncJobItemProcessor<struct CrashItem_t>,1> > : CParallelProcessorAbstract_Base, IMultipleWorkerJob { void* vtable[2]; };
class CParallelProcessorAbstract<class CParallelProcessor<FatalErrorItem_t,class CFuncJobItemProcessor<struct FatalErrorItem_t>,1> > : CParallelProcessorAbstract_Base, IMultipleWorkerJob { void* vtable[2]; };
class CParallelProcessorAbstract<class CParallelProcessor<ReadPacketEntitiesWorkItem_t * __ptr64,class CMemberFuncJobItemProcessor<struct ReadPacketEntitiesWorkItem_t * __ptr64,class CNetworkGameClient,class CNetworkGameClient>,1> > : CParallelProcessorAbstract_Base, IMultipleWorkerJob { void* vtable[2]; };
class CParallelProcessorAbstract<class CParallelProcessor<ReadPacketEntitiesWorkItem_t,class CMemberFuncJobItemProcessor<struct ReadPacketEntitiesWorkItem_t,class CNetworkGameClient,class CNetworkGameClient>,1> > : CParallelProcessorAbstract_Base, IMultipleWorkerJob { void* vtable[2]; };
class CParallelProcessorAbstract<class CReadPacketEntities_ParallelProcessingController> : CParallelProcessorAbstract_Base, IMultipleWorkerJob { void* vtable[2]; };
class CPipedCommandLogRedirector : ILoggingListener { void* vtable[5]; };
class CPlayDemoClientPrerequisite : IPrerequisite { void* vtable[6]; };
class CPostConnectCallback { void* vtable[1]; };
class CPulseCell_Base { void* vtable[12]; };
class CPulseCell_BaseFlow : CPulseCell_Base { void* vtable[12]; };
class CPulseCell_BaseRequirement : CPulseCell_Base { void* vtable[15]; };
class CPulseCell_BaseValue : CPulseCell_Base { void* vtable[12]; };
class CPulseCell_Inflow_BaseEntrypoint : CPulseCell_BaseFlow { void* vtable[12]; };
class CPulseCell_Inflow_Method : CPulseCell_Inflow_BaseEntrypoint { void* vtable[12]; };
class CPulseCell_Inflow_Wait : CPulseCell_BaseYieldingInflow { void* vtable[22]; };
class CPulseCell_Value_RandomFloat : CPulseCell_BaseValue { void* vtable[12]; };
class CPulseCell_Value_RandomInt : CPulseCell_BaseValue { void* vtable[12]; };
class CPulseInterfaceHelpers_Load_NoOp : CKV3TransferInterface_Worldspace_Load_NoOp { void* vtable[2]; };
class CPulseInterfaceHelpers_Load_NoOp : CKV3TransferInterface_EHandle_Load_NoOp { void* vtable[1]; };
class CPulseInterfaceHelpers_Load_NoOp : CKV3TransferInterface_GameTime_Load_NoOp { void* vtable[1]; };
class CPulseInterfaceHelpers_Load_NoOp : CKV3Transfer_EmptyResourceLoadInterface { void* vtable[1]; };
class CPulseInterfaceHelpers_Load_NoOp : CPulseInstanceLoadAPI_NoOp, CKV3TransferInterface_GameTime_Load_NoOp, CKV3TransferInterface_EHandle_Load_NoOp, CKV3TransferInterface_Worldspace_Load_NoOp, CKV3Transfer_EmptyResourceLoadInterface { void* vtable[1]; };
class CPulseInterfaceHelpers_Save_NoOp : CKV3TransferInterface_Worldspace_Save_NoOp { void* vtable[2]; };
class CPulseInterfaceHelpers_Save_NoOp : CKV3TransferInterface_EHandle_Save_NoOp { void* vtable[1]; };
class CPulseInterfaceHelpers_Save_NoOp : CKV3TransferInterface_GameTime_Save_NoOp { void* vtable[1]; };
class CPulseInterfaceHelpers_Save_NoOp : CPulseInstanceSaveAPI_NoOp, CKV3TransferInterface_GameTime_Save_NoOp, CKV3TransferInterface_EHandle_Save_NoOp, CKV3TransferInterface_Worldspace_Save_NoOp { void* vtable[1]; };
class CPulseScopeEnumeratingTypeService : IPulseTypeQueriesForScope { void* vtable[8]; };
class CRConClient : ISocketCreatorListener { void* vtable[3]; };
class CRConServer : ISocketCreatorListener { void* vtable[3]; };
class CRConVProfExport : CTier3AppSystem<IVProfExport,0>, IVProfData { void* vtable[19]; };
class CRConVProfExport : IVProfData { void* vtable[2]; };
class CRealMemoryDemoBuffer : IDemoBuffer { void* vtable[15]; };
class CRefreshRateGetter : IRenderDeviceEventListener { void* vtable[4]; };
class CRegistry : IRegistry { void* vtable[9]; };
class CRenderDevicePresentCallbackClientServer : IRenderDevicePresentCallback { void* vtable[1]; };
class CRenderService : CBaseEngineService<IRenderService>, IToolsResourceListener { void* vtable[37]; };
class CRenderService : IToolsResourceListener { void* vtable[2]; };
class CRenderingWorldSession : ISource2WorldSession, IWorldLoadUnloadCallback { void* vtable[41]; };
class CRenderingWorldSession : IWorldLoadUnloadCallback { void* vtable[2]; };
class CResourceManifestPrerequisite : IPrerequisite { void* vtable[6]; };
class CSVCMsgList_GameEvents : google::protobuf::Message { void* vtable[17]; };
class CSVCMsgList_GameEvents_event_t : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_BSPDecal : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_Broadcast_Command : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_ClassInfo : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_ClassInfo_class_t : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_ClassInfo_t : CSVCMsg_ClassInfo { void* vtable[17]; };
class CSVCMsg_ClassInfo_t : CNetMessagePB<42,CSVCMsg_ClassInfo,10,1,0>, CSVCMsg_ClassInfo { void* vtable[5]; };
class CSVCMsg_ClearAllStringTables : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_ClearAllStringTables_t : CSVCMsg_ClearAllStringTables { void* vtable[17]; };
class CSVCMsg_ClearAllStringTables_t : CNetMessagePB<51,CSVCMsg_ClearAllStringTables,10,1,0>, CSVCMsg_ClearAllStringTables { void* vtable[5]; };
class CSVCMsg_CmdKeyValues : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_CmdKeyValues_t : CBaseCmdKeyValues<CSVCMsg_CmdKeyValues> { void* vtable[17]; };
class CSVCMsg_CmdKeyValues_t : CNetMessagePB<52,CBaseCmdKeyValues<CSVCMsg_CmdKeyValues>,9,1,0>, CBaseCmdKeyValues<CSVCMsg_CmdKeyValues> { void* vtable[5]; };
class CSVCMsg_CreateStringTable : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_CreateStringTable_t : CSVCMsg_CreateStringTable { void* vtable[17]; };
class CSVCMsg_CreateStringTable_t : CNetMessagePB<44,CSVCMsg_CreateStringTable,10,1,0>, CSVCMsg_CreateStringTable { void* vtable[5]; };
class CSVCMsg_CrosshairAngle : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_FixAngle : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_FlattenedSerializer : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_FlattenedSerializerWrapper : CSVCMsg_FlattenedSerializer { void* vtable[17]; };
class CSVCMsg_FlattenedSerializer_t : CSVCMsg_FlattenedSerializerWrapper { void* vtable[17]; };
class CSVCMsg_FlattenedSerializer_t : CNetMessagePB<41,CSVCMsg_FlattenedSerializerWrapper,10,1,0>, CSVCMsg_FlattenedSerializerWrapper { void* vtable[5]; };
class CSVCMsg_FullFrameSplit : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_FullFrameSplit_t : CSVCMsg_FullFrameSplit { void* vtable[17]; };
class CSVCMsg_FullFrameSplit_t : CNetMessagePB<70,CSVCMsg_FullFrameSplit,0,1,0>, CSVCMsg_FullFrameSplit { void* vtable[5]; };
class CSVCMsg_GameEvent : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_GameEventList : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_GameEventList_descriptor_t : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_GameEventList_key_t : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_GameEvent_key_t : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_GameSessionConfiguration : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_GetCvarValue : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_HLTVStatus : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_HltvFixupOperatorStatus : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_HltvReplay : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_HltvReplay_t : CSVCMsg_HltvReplay { void* vtable[17]; };
class CSVCMsg_HltvReplay_t : CNetMessagePB<74,CSVCMsg_HltvReplay,17,1,0>, CSVCMsg_HltvReplay { void* vtable[5]; };
class CSVCMsg_Menu : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_NextMsgPredicted : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_NextMsgPredicted_t : CSVCMsg_NextMsgPredicted { void* vtable[17]; };
class CSVCMsg_NextMsgPredicted_t : CNetMessagePB<77,CSVCMsg_NextMsgPredicted,17,1,0>, CSVCMsg_NextMsgPredicted { void* vtable[5]; };
class CSVCMsg_PacketEntities : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_PacketEntities_alternate_baseline_t : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_PacketEntities_non_transmitted_entities_t : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_PacketEntities_outofpvs_entity_updates_t : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_PacketEntities_t : CSVCMsg_PacketEntities { void* vtable[17]; };
class CSVCMsg_PacketEntities_t : CNetMessagePB<55,CSVCMsg_PacketEntities,-1,1,0>, CSVCMsg_PacketEntities { void* vtable[5]; };
class CSVCMsg_PacketReliable : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_PacketReliable_t : CSVCMsg_PacketReliable { void* vtable[17]; };
class CSVCMsg_PacketReliable_t : CNetMessagePB<61,CSVCMsg_PacketReliable,0,1,0>, CSVCMsg_PacketReliable { void* vtable[5]; };
class CSVCMsg_PeerList : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_PeerList_t : CSVCMsg_PeerList { void* vtable[17]; };
class CSVCMsg_PeerList_t : CNetMessagePB<60,CSVCMsg_PeerList,0,1,0>, CSVCMsg_PeerList { void* vtable[5]; };
class CSVCMsg_Prefetch : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_Print : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_Print_t : CSVCMsg_Print { void* vtable[17]; };
class CSVCMsg_Print_t : CNetMessagePB<48,CSVCMsg_Print,0,1,0>, CSVCMsg_Print { void* vtable[5]; };
class CSVCMsg_RconServerDetails : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_RconServerDetails_t : CSVCMsg_RconServerDetails { void* vtable[17]; };
class CSVCMsg_RconServerDetails_t : CNetMessagePB<71,CSVCMsg_RconServerDetails,0,1,0>, CSVCMsg_RconServerDetails { void* vtable[5]; };
class CSVCMsg_SendTable : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_SendTable_sendprop_t : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_ServerInfo : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_ServerInfo_t : CSVCMsg_ServerInfo { void* vtable[17]; };
class CSVCMsg_ServerInfo_t : CNetMessagePB<40,CSVCMsg_ServerInfo,10,1,0>, CSVCMsg_ServerInfo { void* vtable[5]; };
class CSVCMsg_ServerSteamID : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_ServerSteamID_t : CSVCMsg_ServerSteamID { void* vtable[17]; };
class CSVCMsg_ServerSteamID_t : CNetMessagePB<63,CSVCMsg_ServerSteamID,0,1,1>, CSVCMsg_ServerSteamID { void* vtable[5]; };
class CSVCMsg_SetPause : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_SetPause_t : CSVCMsg_SetPause { void* vtable[17]; };
class CSVCMsg_SetPause_t : CNetMessagePB<43,CSVCMsg_SetPause,0,1,0>, CSVCMsg_SetPause { void* vtable[5]; };
class CSVCMsg_SetView : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_Sounds : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_Sounds_sounddata_t : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_SplitScreen : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_SplitScreen_t : CSVCMsg_SplitScreen { void* vtable[17]; };
class CSVCMsg_SplitScreen_t : CNetMessagePB<54,CSVCMsg_SplitScreen,10,1,0>, CSVCMsg_SplitScreen { void* vtable[5]; };
class CSVCMsg_StopSound : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_TempEntities : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_UpdateStringTable : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_UpdateStringTable_t : CSVCMsg_UpdateStringTable { void* vtable[17]; };
class CSVCMsg_UpdateStringTable_t : CNetMessagePB<45,CSVCMsg_UpdateStringTable,7,1,0>, CSVCMsg_UpdateStringTable { void* vtable[5]; };
class CSVCMsg_UserCommands : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_UserMessage : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_UserMessage_t : CSVCMsg_UserMessage { void* vtable[17]; };
class CSVCMsg_UserMessage_t : CNetMessagePB<72,CSVCMsg_UserMessage,13,1,0>, CSVCMsg_UserMessage { void* vtable[5]; };
class CSVCMsg_VoiceData : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_VoiceData_t : CSVCMsg_VoiceData { void* vtable[17]; };
class CSVCMsg_VoiceData_t : CNetMessagePB<47,CSVCMsg_VoiceData,6,0,0>, CSVCMsg_VoiceData { void* vtable[5]; };
class CSVCMsg_VoiceInit : google::protobuf::Message { void* vtable[17]; };
class CSVCMsg_VoiceInit_t : CSVCMsg_VoiceInit { void* vtable[17]; };
class CSVCMsg_VoiceInit_t : CNetMessagePB<46,CSVCMsg_VoiceInit,10,1,0>, CSVCMsg_VoiceInit { void* vtable[5]; };
class CSceneViewDebugOverlaysListener : ISceneViewDebugOverlaysListener { void* vtable[1]; };
class CSchemaInstallCallback : CPostConnectCallback { void* vtable[1]; };
class CSchemaRegistration_engine2 : CSchemaRegistration { void* vtable[1]; };
class CSchemaRegistration_entity2 : CSchemaRegistration { void* vtable[1]; };
class CScreenshotService : CBaseEngineService<IEngineService>, IScreenshotCallback { void* vtable[23]; };
class CScreenshotService : IScreenshotCallback { void* vtable[5]; };
class CScreenshotServiceReadTexturePixelsCallback : IReadTexturePixelsCallback { void* vtable[3]; };
class CSequentialPrerequisite : IPrerequisite, IPrerequisiteRegistry { void* vtable[8]; };
class CSequentialPrerequisite : IPrerequisiteRegistry { void* vtable[2]; };
class CSerializedEntityPolymorphicFieldsMetadataHelper : IPolymorphicMetadataHelper { void* vtable[1]; };
class CServerConsoleRedirect : IServerConsoleRedirect { void* vtable[4]; };
class CServerGameSessionManifestPrerequisite : CGameResourceManifestPrerequisite, IGameResourceManifestLoadCompletionCallback { void* vtable[7]; };
class CServerGameSessionManifestPrerequisite : IGameResourceManifestLoadCompletionCallback { void* vtable[2]; };
class CServerMsg : IMatchAsyncOperation { void* vtable[10]; };
class CServerMsg_CheckReservation : CServerMsg { void* vtable[10]; };
class CServerRemoteAccess : IGameServerData, IScreenshotCallback { void* vtable[5]; };
class CServerRemoteAccess : IScreenshotCallback { void* vtable[5]; };
class CServerSideClient : CServerSideClientBase, INetworkChannelNotify, INetworkMessageProcessingPreFilter { void* vtable[79]; };
class CServerSideClient : INetworkMessageProcessingPreFilter { void* vtable[1]; };
class CServerSideClient::CSendJob_Empty : CAsyncCallJob<CServerSideClient,CServerSideClient::SendSnapshotJob_Empty_t>, CRefCountServiceBase<CRefMT> { void* vtable[9]; };
class CServerSideClient::CSendJob_HltvReplay : CAsyncCallJob<CServerSideClient,CServerSideClient::SendSnapshotJob_HltvReplay_t>, CRefCountServiceBase<CRefMT> { void* vtable[9]; };
class CServerSideClient::CSendJob_HltvSource : CAsyncCallJob<CServerSideClient,CServerSideClient::SendSnapshotJob_HltvSource_t>, CRefCountServiceBase<CRefMT> { void* vtable[9]; };
class CServerSideClient::CSendJob_Regular : CThreadedJobWithDependencies, CRefCountServiceBase<CRefMT> { void* vtable[9]; };
class CServerSideClientBase : CUtlSlot, INetworkChannelNotify, INetworkMessageProcessingPreFilter { void* vtable[79]; };
class CServerSideClientBase : INetworkMessageProcessingPreFilter { void* vtable[1]; };
class CSimpleLoggingListener : ILoggingListener { void* vtable[5]; };
class CSimpleWindowsLoggingListener : ILoggingListener { void* vtable[5]; };
class CSoundService : CBaseEngineService<ISoundService> { void* vtable[37]; };
class CSource1InputHandlerPostClientHandler : IInputHandler { void* vtable[1]; };
class CSource1InputHandlerPreClientHandler : IInputHandler { void* vtable[1]; };
class CSource1InputHandler_Client : IInputHandler { void* vtable[1]; };
class CSource2Metrics_FetchMapData_Request : google::protobuf::Message { void* vtable[17]; };
class CSource2Metrics_FetchMapData_Response : google::protobuf::Message { void* vtable[17]; };
class CSource2Metrics_FetchMapData_Response_MapData : google::protobuf::Message { void* vtable[17]; };
class CSource2Metrics_MatchPerfSummary_Notification : google::protobuf::Message { void* vtable[17]; };
class CSource2Metrics_MatchPerfSummary_Notification_Client : google::protobuf::Message { void* vtable[17]; };
class CSource2Metrics_RecordPlayStats_Notification : google::protobuf::Message { void* vtable[17]; };
class CSpawnServerPrerequisite : IPrerequisite { void* vtable[6]; };
class CSplitScreenService : CBaseEngineService<ISplitScreenService>, IMobileEventListener { void* vtable[43]; };
class CSplitScreenService : IMobileEventListener { void* vtable[4]; };
class CStatsService : CBaseEngineService<IStatsService>, IDebugVisualizer { void* vtable[27]; };
class CStatsService : IDebugVisualizer { void* vtable[6]; };
class CStdFunctionJob : CThreadedJob, CRefCountServiceBase<CRefMT> { void* vtable[7]; };
class CTextConsole { void* vtable[17]; };
class CTextConsoleWin : CTextConsole { void* vtable[17]; };
class CTextOnlyLoggingListener : ILoggingListener { void* vtable[5]; };
class CThreadedDependentJob : CThreadedJob, CRefCountServiceBase<CRefMT> { void* vtable[8]; };
class CThreadedFileLogger : CThreadedLogger { void* vtable[5]; };
class CThreadedJob : CRefCounted1<IRefCounted,CRefCountServiceBase<CRefMT> >, CRefCountServiceBase<CRefMT> { void* vtable[7]; };
class CThreadedJobWithDependencies : CThreadedDependentJob, CRefCountServiceBase<CRefMT> { void* vtable[9]; };
class CThreadedLogger { void* vtable[5]; };
class CTier1Application : CTier1AppSystem<IApplication,0> { void* vtable[62]; };
class CTier2AppSystemDict : CTier1AppSystemDict { void* vtable[7]; };
class CTier2Application : CTier1Application { void* vtable[62]; };
class CToolService : CBaseEngineService<IToolService> { void* vtable[91]; };
class CTvDirectDemoRecorder : ITvStreamSource { void* vtable[10]; };
class CTvDirectDemoRecorder : ITvStreamSink, ITvStreamSource, IDemoMessageSink { void* vtable[5]; };
class CTvDirectDemoRecorder : IDemoMessageSink { void* vtable[1]; };
class CUGCAddonPathResolver : IUGCAddonPathResolver { void* vtable[1]; };
class CVConActivateMessage : IVConCommDataReceived { void* vtable[1]; };
class CVConAutoCompleteHelper : IVConCommDataReceived { void* vtable[1]; };
class CVConCommandMessage : IVConCommDataReceived { void* vtable[1]; };
class CVConsole2FlattenedSerializerListener : IVConsole2FlattenedSerializerListener { void* vtable[7]; };
class CVProfService : CBaseEngineService<IVProfService>, IVConCommDataReceived, IScreenshotCallback { void* vtable[25]; };
class CVProfService : IScreenshotCallback { void* vtable[5]; };
class CVProfService : IVConCommDataReceived { void* vtable[1]; };
class CVariantSaveDataOps : CDefSaveRestoreOps { void* vtable[6]; };
class CVisRender : IDebugVisualizer { void* vtable[6]; };
class CWaitForGameServerStartupPrerequisite : IPrerequisite { void* vtable[6]; };
class CWaitForInitialSpawnGroupsPrerequisite : IPrerequisite { void* vtable[6]; };
class DNameStatusNode : DNameNode { void* vtable[4]; };
class Etc::Block4x4Encoding { void* vtable[8]; };
class Etc::Block4x4Encoding_ETC1 : Etc::Block4x4Encoding { void* vtable[8]; };
class Etc::Block4x4Encoding_R11 : Etc::Block4x4Encoding_RGB8 { void* vtable[8]; };
class Etc::Block4x4Encoding_RG11 : Etc::Block4x4Encoding_R11 { void* vtable[8]; };
class Etc::Block4x4Encoding_RGB8 : Etc::Block4x4Encoding_ETC1 { void* vtable[8]; };
class Etc::Block4x4Encoding_RGB8A1 : Etc::Block4x4Encoding_RGB8 { void* vtable[8]; };
class Etc::Block4x4Encoding_RGB8A1_Opaque : Etc::Block4x4Encoding_RGB8A1 { void* vtable[8]; };
class Etc::Block4x4Encoding_RGB8A1_Transparent : Etc::Block4x4Encoding_RGB8A1 { void* vtable[8]; };
class Etc::Block4x4Encoding_RGBA8 : Etc::Block4x4Encoding_RGB8 { void* vtable[8]; };
class Etc::Block4x4Encoding_RGBA8_Opaque : Etc::Block4x4Encoding_RGBA8 { void* vtable[8]; };
class Etc::Block4x4Encoding_RGBA8_Transparent : Etc::Block4x4Encoding_RGBA8 { void* vtable[8]; };
class GameSessionConfiguration_t : CBaseCmdKeyValues<CSVCMsg_GameSessionConfiguration> { void* vtable[17]; };
class IAssertionFailureListener { void* vtable[3]; };
class IAudioStreamRecorder { void* vtable[3]; };
class IBaseInterface { void* vtable[1]; };
class IConnectionlessPacketHandler { void* vtable[2]; };
class IDebugVisualizer { void* vtable[6]; };
class IDemoMessage { void* vtable[6]; };
class IDemoPlayer { void* vtable[42]; };
class IDemoRecorder : IDemoRecorderBase { void* vtable[20]; };
class IDemoStream { void* vtable[8]; };
class IEngineGameUI : IAppSystem { void* vtable[15]; };
class IEngineService : IAppSystem { void* vtable[23]; };
class IEntityReport { void* vtable[6]; };
class IFlattenedSerializerSpewFunc { void* vtable[3]; };
class IFlattenedSerializerSpewListener { void* vtable[6]; };
class IMobileEventListener { void* vtable[4]; };
class IMultipleWorkerJob { void* vtable[2]; };
class INetPacketMemoryCustomAlloc { void* vtable[2]; };
class INetworkStringDict { void* vtable[9]; };
class INetworkStringTable { void* vtable[17]; };
class INetworkStringTableContainer : IAppSystem { void* vtable[18]; };
class IPrerequisite { void* vtable[6]; };
class IProceduralLayerRenderer { void* vtable[3]; };
class IRenderReadCallback { void* vtable[2]; };
class NetMessageConnectionClosed : google::protobuf::Message { void* vtable[17]; };
class NetMessageConnectionCrashed : google::protobuf::Message { void* vtable[17]; };
class NetMessagePacketEnd : google::protobuf::internal::ZeroFieldsBase { void* vtable[17]; };
class NetMessagePacketStart : google::protobuf::internal::ZeroFieldsBase { void* vtable[17]; };
class NetMessageSplitscreenUserChanged : google::protobuf::Message { void* vtable[17]; };
class PacketEntitiesFilter : INetworkMessageProcessingPreFilter { void* vtable[1]; };
class ProtoFlattenedSerializerField_t : google::protobuf::Message { void* vtable[17]; };
class ProtoFlattenedSerializerField_t_polymorphic_field_t : google::protobuf::Message { void* vtable[17]; };
class ProtoFlattenedSerializer_t : google::protobuf::Message { void* vtable[17]; };
class charNode : DNameNode { void* vtable[4]; };
class pDNameNode : DNameNode { void* vtable[4]; };
class pairNode : DNameNode { void* vtable[4]; };
class pcharNode : DNameNode { void* vtable[4]; };
struct CGameResourceManifest::CCallbackInternal_Steam_OnUGCDownload : CCallbackImpl<24> { void* vtable[4]; };
struct NetPacketCustomAlloc_std_string : INetPacketMemoryCustomAlloc { void* vtable[2]; };
