class CAsyncFileSystem2 : CTier2AppSystem<IAsyncFileSystem2,0> { void* vtable[25]; };
class CAsyncFileSystem2::CBarrierRequest : CAsyncFileSystem2::IRequest { void* vtable[2]; };
class CAsyncFileSystem2::CCompletionQueue : IIOCompletionQueue { void* vtable[2]; };
class CAsyncFileSystem2::CIOServiceThread : CThread { void* vtable[6]; };
class CAsyncFileSystem2::CReadRequestBuilder : IAsyncFileSystem2::IReadRequestBuilder { void* vtable[2]; };
class CAsyncFileSystem2::CReadRequestHandle : IAsyncReadRequest2, CAsyncFileSystem2::IRequest, std::enable_shared_from_this<CAsyncFileSystem2::CReadRequestHandle> { void* vtable[11]; };
class CAsyncFileSystem2::CReadRequestHandle : CAsyncFileSystem2::IRequest { void* vtable[2]; };
class CAsyncFileSystem2::CWriteRequestBuilder : IAsyncFileSystem2::IWriteRequestBuilder { void* vtable[2]; };
class CAsyncFileSystem2::CWriteRequestHandle : IAsyncWriteRequest2, CAsyncFileSystem2::IRequest, std::enable_shared_from_this<CAsyncFileSystem2::CWriteRequestHandle> { void* vtable[7]; };
class CAsyncFileSystem2::CWriteRequestHandle : CAsyncFileSystem2::IRequest { void* vtable[2]; };
class CBaseFileSystem : CTier2AppSystem<IFileSystem,0> { void* vtable[129]; };
class CBaseVModuleMetadataProvider { void* vtable[1]; };
class CBufferStream : IWriteStream { void* vtable[2]; };
class CFileHandle { void* vtable[1]; };
class CFileStream : IWriteStream { void* vtable[2]; };
class CFileSystem_Stdio : CBaseFileSystem { void* vtable[129]; };
class CFioReadOnlyFile : CStdFilesystemFile { void* vtable[11]; };
class CFioReadOnlyMemoryMappedFile : IMemoryMappedFile { void* vtable[3]; };
class CIODelayAlarmThread : CThread { void* vtable[6]; };
class CMemoryMappedFileSection : IMemoryMappedFile { void* vtable[3]; };
class CMemoryMappedFileSection_SelfDelete : CMemoryMappedFileSection { void* vtable[3]; };
class CModuleMetadataProvider_ResourceManifests : CBaseVModuleMetadataProvider { void* vtable[1]; };
class CPackedStoreMemoryMappedFile : IMemoryMappedFile { void* vtable[3]; };
class CPackedStoreMemoryMappedFile_HierarchicalParent : CPackedStoreMemoryMappedFile { void* vtable[3]; };
class CPostConnectCallback { void* vtable[1]; };
class CSchemaInstallCallback : CPostConnectCallback { void* vtable[1]; };
class CStdFilesystemFile { void* vtable[11]; };
class CStdioFile : CStdFilesystemFile { void* vtable[11]; };
class CZip : IZip { void* vtable[21]; };
class IAsyncFileSystem2::IReadRequestBuilder { void* vtable[2]; };
class IAsyncFileSystem2::IWriteRequestBuilder { void* vtable[2]; };
class IAsyncReadRequest2 { void* vtable[11]; };
class IAsyncWriteRequest2 { void* vtable[7]; };
class IIOCompletionQueue { void* vtable[2]; };
class IMemoryMappedFile { void* vtable[3]; };
