class CAimConstraint : CBaseConstraint { void* vtable[15]; };
class CAnimSkeleton : CMutableRefCounted<CMutableRefCountBase<CRefMT> > { void* vtable[4]; };
class CBaseAppSystem<VPhys2HandleInterface> : VPhys2HandleInterface {};
class CBaseAppSystem<class IVPhysics2> : IVPhysics2 {};
class CBaseConstraint : CBoneConstraintBase { void* vtable[15]; };
class CBaseIntrospectedToKV3TypeManager : IResourceTypeManager { void* vtable[22]; };
class CBaseVModuleMetadataProvider { void* vtable[1]; };
class CBoneConstraintBase { void* vtable[14]; };
class CBoneConstraintDotToMorph : CBoneConstraintBase { void* vtable[14]; };
class CBoneConstraintPoseSpaceBone : CBaseConstraint { void* vtable[15]; };
class CBoneConstraintPoseSpaceMorph : CBoneConstraintBase { void* vtable[14]; };
class CBoneConstraintRbf : CBoneConstraintBase { void* vtable[14]; };
class CBreakLegacyParser : IVPhysicsLegacyKeyHandler { void* vtable[2]; };
class CDataDescConvertor : IDataDescConvertor { void* vtable[1]; };
class CDefSaveRestoreOps : ISaveRestoreOps {};
class CDefaultKV3TransferResourceTypeManager<440006964086> : CKV3ResourceTypeManager<440006964086> {};
class CDualHullAgglomerator : CFeAgglomerator { void* vtable[1]; };
class CEmptySequence : ISequence { void* vtable[61]; };
class CFeAgglomerator { void* vtable[1]; };
class CFnPhysicsAnyJointImpl : CFnPhysicsJointBaseImpl<IFnPhysicsAnyJoint> { void* vtable[16]; };
class CFnPhysicsAnyShapeImpl : CFnPhysicsShapeBaseImpl<IFnPhysicsAnyShape> { void* vtable[29]; };
class CFnPhysicsBodyImpl : IFnPhysicsBody { void* vtable[44]; };
class CFnPhysicsCapsuleShapeImpl : CFnPhysicsShapeBaseImpl<IFnPhysicsCapsuleShape> { void* vtable[30]; };
class CFnPhysicsConicalJointImpl : CFnPhysicsJointBaseImpl<IFnPhysicsConicalJoint> { void* vtable[41]; };
class CFnPhysicsContactImpl : IFnPhysicsContact { void* vtable[24]; };
class CFnPhysicsGenericJointImpl : CFnPhysicsJointBaseImpl<IFnPhysicsGenericJoint> { void* vtable[35]; };
class CFnPhysicsHullShapeImpl : CFnPhysicsShapeBaseImpl<IFnPhysicsHullShape> { void* vtable[37]; };
class CFnPhysicsJointBaseImpl<class IFnPhysicsAnyJoint> : IFnPhysicsAnyJoint {};
class CFnPhysicsJointBaseImpl<class IFnPhysicsConicalJoint> : IFnPhysicsConicalJoint {};
class CFnPhysicsJointBaseImpl<class IFnPhysicsGenericJoint> : IFnPhysicsGenericJoint {};
class CFnPhysicsJointBaseImpl<class IFnPhysicsPrismaticJoint> : IFnPhysicsPrismaticJoint {};
class CFnPhysicsJointBaseImpl<class IFnPhysicsPulleyJoint> : IFnPhysicsPulleyJoint {};
class CFnPhysicsJointBaseImpl<class IFnPhysicsRevoluteJoint> : IFnPhysicsRevoluteJoint {};
class CFnPhysicsJointBaseImpl<class IFnPhysicsSphericalJoint> : IFnPhysicsSphericalJoint {};
class CFnPhysicsJointBaseImpl<class IFnPhysicsSplineJoint> : IFnPhysicsSplineJoint {};
class CFnPhysicsJointBaseImpl<class IFnPhysicsSpringJoint> : IFnPhysicsSpringJoint {};
class CFnPhysicsJointBaseImpl<class IFnPhysicsWeldJoint> : IFnPhysicsWeldJoint {};
class CFnPhysicsJointBaseImpl<class IFnPhysicsWheelJoint> : IFnPhysicsWheelJoint {};
class CFnPhysicsMeshShapeImpl : CFnPhysicsShapeBaseImpl<IFnPhysicsMeshShape> { void* vtable[42]; };
class CFnPhysicsPrismaticJointImpl : CFnPhysicsJointBaseImpl<IFnPhysicsPrismaticJoint> { void* vtable[37]; };
class CFnPhysicsPulleyJointImpl : CFnPhysicsJointBaseImpl<IFnPhysicsPulleyJoint> { void* vtable[30]; };
class CFnPhysicsRevoluteJointImpl : CFnPhysicsJointBaseImpl<IFnPhysicsRevoluteJoint> { void* vtable[37]; };
class CFnPhysicsShapeBaseImpl<class IFnPhysicsAnyShape> : IFnPhysicsAnyShape {};
class CFnPhysicsShapeBaseImpl<class IFnPhysicsCapsuleShape> : IFnPhysicsCapsuleShape {};
class CFnPhysicsShapeBaseImpl<class IFnPhysicsHullShape> : IFnPhysicsHullShape {};
class CFnPhysicsShapeBaseImpl<class IFnPhysicsMeshShape> : IFnPhysicsMeshShape {};
class CFnPhysicsShapeBaseImpl<class IFnPhysicsSphereShape> : IFnPhysicsSphereShape {};
class CFnPhysicsSoftbodyImpl : IFnPhysicsSoftbody { void* vtable[50]; };
class CFnPhysicsSphereShapeImpl : CFnPhysicsShapeBaseImpl<IFnPhysicsSphereShape> { void* vtable[30]; };
class CFnPhysicsSphericalJointImpl : CFnPhysicsJointBaseImpl<IFnPhysicsSphericalJoint> { void* vtable[29]; };
class CFnPhysicsSplineJointImpl : CFnPhysicsJointBaseImpl<IFnPhysicsSplineJoint> { void* vtable[28]; };
class CFnPhysicsSpringJointImpl : CFnPhysicsJointBaseImpl<IFnPhysicsSpringJoint> { void* vtable[27]; };
class CFnPhysicsWeldJointImpl : CFnPhysicsJointBaseImpl<IFnPhysicsWeldJoint> { void* vtable[29]; };
class CFnPhysicsWheelJointImpl : CFnPhysicsJointBaseImpl<IFnPhysicsWheelJoint> { void* vtable[50]; };
class CFnPhysicsWorldImpl : IFnPhysicsWorld { void* vtable[26]; };
class CFootTrajectory : IFootTrajectory { void* vtable[3]; };
class CIkSolver : IIkSolver { void* vtable[24]; };
class CIntersectionController : IPhysIntersectionController { void* vtable[14]; };
class CIntersectionDictionary : IPhysIntersectionDictionary { void* vtable[20]; };
class CKV3ResourceBlockHelper : IAsyncProcessedDataResult { void* vtable[1]; };
class CKV3ResourceTypeManager<440006964086> : IResourceTypeManager {};
class CKV3TransferContextBase : IErrorListener { void* vtable[6]; };
class CKV3TransferLoadContext : CKV3TransferContextBase { void* vtable[6]; };
class CKV3TransferSaveContext : CKV3TransferContextBase { void* vtable[6]; };
class CKV3Transfer_ResourceLoadInterface : IKV3TransferInterface_ResourceLoad { void* vtable[1]; };
class CModelConfigElement { void* vtable[8]; };
class CModelConfigElement_AttachedModel : CModelConfigElement { void* vtable[8]; };
class CModelConfigElement_Command : CModelConfigElement { void* vtable[8]; };
class CModelConfigElement_RandomColor : CModelConfigElement { void* vtable[8]; };
class CModelConfigElement_RandomPick : CModelConfigElement { void* vtable[8]; };
class CModelConfigElement_SetBodygroup : CModelConfigElement { void* vtable[8]; };
class CModelConfigElement_SetBodygroupOnAttachedModels : CModelConfigElement { void* vtable[8]; };
class CModelConfigElement_SetMaterialGroup : CModelConfigElement { void* vtable[8]; };
class CModelConfigElement_SetMaterialGroupOnAttachedModels : CModelConfigElement { void* vtable[8]; };
class CModelConfigElement_SetRenderColor : CModelConfigElement { void* vtable[8]; };
class CModelConfigElement_UserPick : CModelConfigElement { void* vtable[8]; };
class CModuleMetadataProvider_ResourceManifests : CBaseVModuleMetadataProvider { void* vtable[1]; };
class CMorphConstraint : CBaseConstraint { void* vtable[15]; };
class CMutableRefCountBase<class CRefMT> {};
class CMutableRefCounted<class CMutableRefCountBase<class CRefMT> > : CMutableRefCountBase<CRefMT> {};
class COrientConstraint : CBaseConstraint { void* vtable[15]; };
class CParentConstraint : CBaseConstraint { void* vtable[15]; };
class CPhysAggregateInstance : IPhysAggregateInstance { void* vtable[75]; };
class CPhysDataTypeManager : CTypesafeIntrospectedToKV3TypeManager<495958126710,VPhysXAggregateData_t> { void* vtable[25]; };
class CPhysicsAbsoluteRagdollControl : IPhysicsRagdollControl { void* vtable[20]; };
class CPhysicsBody : IPhysicsBody { void* vtable[148]; };
class CPhysicsCharacterProxy : IPhysicsCharacterProxy { void* vtable[18]; };
class CPhysicsFrictionSnapshot : IPhysicsFrictionSnapshot { void* vtable[10]; };
class CPhysicsJoint : IPhysicsJoint { void* vtable[67]; };
class CPhysicsMotionController : IPhysicsMotionController { void* vtable[11]; };
class CPhysicsParticleRope : IPhysicsParticleRope { void* vtable[107]; };
class CPhysicsRagdoll : IPhysicsRagdoll { void* vtable[33]; };
class CPhysicsRagdollAggregate : IPhysAggregateInstance { void* vtable[75]; };
class CPhysicsRope : IPhysicsRope { void* vtable[10]; };
class CPhysicsRopeLink : IPhysicsRopeLink { void* vtable[14]; };
class CPhysicsShadowController : IPhysicsShadowController { void* vtable[12]; };
class CPhysicsShape : IPhysicsShape { void* vtable[63]; };
class CPhysicsSoftbody : IPhysicsSoftbody { void* vtable[130]; };
class CPhysicsVehicle : IPhysicsVehicle { void* vtable[91]; };
class CPointConstraint : CBaseConstraint { void* vtable[15]; };
class CPostConnectCallback { void* vtable[1]; };
class CRefCountServiceBase<class CRefMT> {};
class CRefCounted1<class IRefCounted,class CRefCountServiceBase<class CRefMT> > : IRefCounted, CRefCountServiceBase<CRefMT> {};
class CRefCounted<class CRefCountServiceBase<class CRefMT> > : CRefCountServiceBase<CRefMT> {};
class CRenderMesh : CRefCounted<CRefCountServiceBase<CRefMT> > { void* vtable[4]; };
class CResourceStream : CResourceStreamBase {};
class CResourceStreamBase { void* vtable[2]; };
class CResourceStreamFixed : CResourceStream { void* vtable[2]; };
class CResourceStreamUnaligned : CResourceStreamBase {};
class CResourceStreamUnalignedGrowable : CResourceStreamUnaligned { void* vtable[2]; };
class CRnBlockWeldJoint : CRnWeldJoint { void* vtable[12]; };
class CRnCapsuleShape : CRnShape { void* vtable[29]; };
class CRnConicalJoint : CRnJoint { void* vtable[12]; };
class CRnContact : CRnOverlappingPair { void* vtable[8]; };
class CRnConvexContact : CRnContact { void* vtable[8]; };
class CRnGenericJoint : CRnJoint { void* vtable[12]; };
class CRnHullShape : CRnShape { void* vtable[29]; };
class CRnJoint : CRnSolverJoint { void* vtable[12]; };
class CRnLink { void* vtable[1]; };
class CRnLinkage { void* vtable[4]; };
class CRnMeshContact : CRnContact { void* vtable[8]; };
class CRnMeshShape : CRnShape { void* vtable[29]; };
class CRnNullJoint : CRnJoint { void* vtable[13]; };
class CRnOverlappingPair { void* vtable[1]; };
class CRnPrismaticBlockJoint : CRnPrismaticJoint { void* vtable[12]; };
class CRnPrismaticJoint : CRnJoint { void* vtable[12]; };
class CRnPulleyJoint : CRnJoint { void* vtable[12]; };
class CRnQueryCache : IPhysicsQueryCache { void* vtable[6]; };
class CRnRevoluteBlockJoint : CRnRevoluteJoint { void* vtable[12]; };
class CRnRevoluteJoint : CRnJoint { void* vtable[12]; };
class CRnRope : CRnLinkage { void* vtable[4]; };
class CRnRopeLink : CRnLink { void* vtable[1]; };
class CRnShape { void* vtable[29]; };
class CRnSolverJoint {};
class CRnSphereShape : CRnShape { void* vtable[29]; };
class CRnSphericalJoint : CRnJoint { void* vtable[12]; };
class CRnSplineJoint : CRnJoint { void* vtable[12]; };
class CRnSpringJoint : CRnJoint { void* vtable[12]; };
class CRnTautRopeSection : CRnLinkage { void* vtable[4]; };
class CRnTautRopeSectionLink : CRnLink { void* vtable[1]; };
class CRnVehicle : CRnLinkage { void* vtable[6]; };
class CRnWeldJoint : CRnJoint { void* vtable[12]; };
class CRnWheelContact : CRnContact { void* vtable[8]; };
class CRnWheelJoint : CRnJoint { void* vtable[12]; };
class CSchemaInstallCallback : CPostConnectCallback { void* vtable[1]; };
class CSchemaRegistration {};
class CSchemaRegistration_modellib : CSchemaRegistration { void* vtable[1]; };
class CSchemaRegistration_physicslib : CSchemaRegistration { void* vtable[1]; };
class CSchemaRegistration_vphysics2 : CSchemaRegistration { void* vtable[1]; };
class CSerialStreamBufferManager : CStackTranslationHelperModuleMappingListener, IStackTranslationHelperFactory { void* vtable[3]; };
class CSerialStreamBufferManager : IStackTranslationHelperFactory { void* vtable[1]; };
class CSerialStreamSnapshot : IPhysSerialStreamSnapshot { void* vtable[15]; };
class CSoftbodyEffect : ISoftbodyEffect { void* vtable[9]; };
class CSoftbodyEffectDampenVelocity : CSoftbodyEffect { void* vtable[9]; };
class CSoftbodyEffectGravity : CSoftbodyEffect { void* vtable[9]; };
class CSoftbodyEffectPressurize : CSoftbodyEffect { void* vtable[9]; };
class CSoftbodyEffectSkinnedCollider : CSoftbodyEffect { void* vtable[9]; };
class CSoftbodyEffectSpeedup : CSoftbodyEffect { void* vtable[9]; };
class CSoftbodyEffectStiffen : CSoftbodyEffect { void* vtable[9]; };
class CSoftbodyEffectWind : CSoftbodyEffect { void* vtable[9]; };
class CSpaceAgnosticBoneAccessor : IPoseAccessor { void* vtable[9]; };
class CStackTranslationHelper {};
class CStackTranslationHelperModuleMappingListener : IModuleMappingListener, IStackTranslationHelperFactory { void* vtable[3]; };
class CStackTranslationHelperModuleMappingListener : IStackTranslationHelperFactory { void* vtable[1]; };
class CStackTranslationHelper_Universal : CStackTranslationHelper { void* vtable[17]; };
class CStackTranslationHelper_VSymbolModule : CStackTranslationHelper { void* vtable[18]; };
class CStackTranslationHelper_VirtualMachine : CStackTranslationHelper { void* vtable[17]; };
class CThreadedJob : CRefCounted1<IRefCounted,CRefCountServiceBase<CRefMT> >, CRefCountServiceBase<CRefMT> { void* vtable[7]; };
class CTier0AppSystem<VPhys2HandleInterface,0> : CBaseAppSystem<VPhys2HandleInterface> {};
class CTier0AppSystem<class IVPhysics2,0> : CBaseAppSystem<IVPhysics2> {};
class CTier1AppSystem<VPhys2HandleInterface,0> : CTier0AppSystem<VPhys2HandleInterface,0> {};
class CTier1AppSystem<class IVPhysics2,0> : CTier0AppSystem<IVPhysics2,0> {};
class CTier2AppSystem<VPhys2HandleInterface,0> : CTier1AppSystem<VPhys2HandleInterface,0> {};
class CTier2AppSystem<class IVPhysics2,0> : CTier1AppSystem<IVPhysics2,0> {};
class CTiltTwistConstraint : CBaseConstraint { void* vtable[15]; };
class CTraceAABB : ITraceObject { void* vtable[2]; };
class CTraceCapsule : ITraceObject { void* vtable[2]; };
class CTraceCloud : ITraceObject { void* vtable[2]; };
class CTraceHull : ITraceObject { void* vtable[2]; };
class CTraceOBB : CTraceWorldspaceCloud { void* vtable[2]; };
class CTracePoint : ITraceObject { void* vtable[2]; };
class CTraceTriangle : ITraceObject { void* vtable[2]; };
class CTraceWorldspaceCloud : ITraceObject { void* vtable[2]; };
class CTwistConstraint : CBaseConstraint { void* vtable[15]; };
class CTypesafeIntrospectedToKV3TypeManager<495958126710,VPhysXAggregateData_t> : CBaseIntrospectedToKV3TypeManager {};
class CTypesafeIntrospectedToKV3TypeManager<495958126710,VPhysXAggregateData_t>::IKV3ResourceAllocatorUtils {};
class CTypesafeIntrospectedToKV3TypeManager<495958126710,VPhysXAggregateData_t>::IKV3ResourceDeallocatorUtils {};
class CVPhys2DebugShape : IRnDebugShape { void* vtable[17]; };
class CVPhys2HandleInterfaceImpl : CTier2AppSystem<VPhys2HandleInterface,0> { void* vtable[12]; };
class CVPhys2World : IVPhysics2World, IPhysReflContext { void* vtable[259]; };
class CVPhys2World : IPhysReflContext { void* vtable[4]; };
class CVPhysKV3TransferLoadContext : CKV3TransferLoadContext { void* vtable[6]; };
class CVPhysKV3TransferSaveContext : CKV3TransferSaveContext { void* vtable[6]; };
class CVPhysPtrSaveRestoreOps : CDefSaveRestoreOps { void* vtable[6]; };
class CVPhysPtrUtlVectorSaveRestoreOps : CVPhysPtrSaveRestoreOps { void* vtable[6]; };
class CVPhysics2ConComm : IVConCommDataReceived { void* vtable[1]; };
class CVPhysics2Interface : CTier2AppSystem<IVPhysics2,0> { void* vtable[128]; };
class CVPhysics2SurfaceProperyManager : CDefaultKV3TransferResourceTypeManager<440006964086>, IPhysSurfacePropertyController { void* vtable[24]; };
class CVPhysics2SurfaceProperyManager : IPhysSurfacePropertyController { void* vtable[8]; };
class CWorldStepJob : CThreadedJob, CRefCountServiceBase<CRefMT> { void* vtable[7]; };
class IAppSystem {};
class IAsyncProcessedDataResult { void* vtable[1]; };
class IBaseSequence {};
class IDataDescConvertor : CRefCounted<CRefCountServiceBase<CRefMT> > {};
class IErrorListener {};
class IFnPhysicsAnyJoint : IFnPhysicsJoint {};
class IFnPhysicsAnyShape : IFnPhysicsShape {};
class IFnPhysicsBody {};
class IFnPhysicsCapsuleShape : IFnPhysicsShape {};
class IFnPhysicsConicalJoint : IFnPhysicsJoint {};
class IFnPhysicsContact {};
class IFnPhysicsGenericJoint : IFnPhysicsJoint {};
class IFnPhysicsHullShape : IFnPhysicsShape {};
class IFnPhysicsJoint {};
class IFnPhysicsMeshShape : IFnPhysicsShape {};
class IFnPhysicsPrismaticJoint : IFnPhysicsJoint {};
class IFnPhysicsPulleyJoint : IFnPhysicsJoint {};
class IFnPhysicsRevoluteJoint : IFnPhysicsJoint {};
class IFnPhysicsShape {};
class IFnPhysicsSoftbody {};
class IFnPhysicsSphereShape : IFnPhysicsShape {};
class IFnPhysicsSphericalJoint : IFnPhysicsJoint {};
class IFnPhysicsSplineJoint : IFnPhysicsJoint {};
class IFnPhysicsSpringJoint : IFnPhysicsJoint {};
class IFnPhysicsWeldJoint : IFnPhysicsJoint {};
class IFnPhysicsWheelJoint : IFnPhysicsJoint {};
class IFnPhysicsWorld {};
class IFootTrajectory {};
class IIkSolver {};
class IKV3TransferInterface_ResourceLoad {};
class IModuleMappingListener {};
class IMotionEvent {};
class IMultipleWorkerJob { void* vtable[2]; };
class IPhysAggregateInstance : IPhysicsBodyList { void* vtable[75]; };
class IPhysIntersectionController { void* vtable[14]; };
class IPhysIntersectionDictionary { void* vtable[20]; };
class IPhysReflContext {};
class IPhysSerialStreamSnapshot { void* vtable[15]; };
class IPhysSurfacePropertyController { void* vtable[8]; };
class IPhysicsBody {};
class IPhysicsBodyList {};
class IPhysicsCharacterProxy {};
class IPhysicsFrictionSnapshot {};
class IPhysicsJoint {};
class IPhysicsMotionController { void* vtable[11]; };
class IPhysicsParticleRope {};
class IPhysicsQueryCache { void* vtable[6]; };
class IPhysicsRagdoll : IPhysicsBodyList {};
class IPhysicsRagdollControl {};
class IPhysicsRope {};
class IPhysicsRopeLink {};
class IPhysicsShadowController {};
class IPhysicsShape {};
class IPhysicsSoftbody {};
class IPhysicsVehicle {};
class IPoseAccessor { void* vtable[9]; };
class IRefCounted {};
class IResourceTypeManager {};
class IRnDebugShape { void* vtable[17]; };
class ISaveRestoreOps {};
class ISoftbodyEffect {};
class IStackTranslationHelperFactory {};
class ITraceObject { void* vtable[2]; };
class IVConCommDataReceived {};
class IVPhysics2 : IAppSystem { void* vtable[128]; };
class IVPhysics2World {};
class IVPhysicsLegacyKeyHandler {};
struct CBaseIntrospectedToKV3TypeManager::AsyncProcessResult : IAsyncProcessedDataResult { void* vtable[1]; };
struct CMorphSetData : CRefCounted<CRefCountServiceBase<CRefMT> > { void* vtable[2]; };
struct PhysicsAsyncProcessResult : IAsyncProcessedDataResult { void* vtable[1]; };
struct VPhys2HandleInterface : IAppSystem {};
